const Node menu[] = {
    {Kind::Item, L"Show Help", IDM_SHOWHOTKEYS, Enabled(), {}},
    {Kind::Separator, L"", 0, 0, {}},
    {Kind::Popup,
     L"Navigate",
     0,
     0,
     {
         {Kind::Item, L"Back", IDM_BACK, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Center View Here", IDM_CENTERVIEW, Enabled(), {}},
         {Kind::Item, L"Zoom In Here", IDM_ZOOMIN, Enabled(), {}},
         {Kind::Item, L"Zoom Out", IDM_ZOOMOUT, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Autozoom Default", IDM_AUTOZOOM_DEFAULT, Enabled(), {}},
         {Kind::Item, L"Autozoom Max", IDM_AUTOZOOM_MAX, Enabled(), {}},
     }},
    {Kind::Popup,
     L"Built-In Views",
     0,
     0,
     {
         {Kind::Item, L"Help", IDM_VIEWS_HELP, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"&Standard View", IDM_STANDARDVIEW, Enabled(), {}},
         {Kind::Item, L"#1 - 4x64 GPU Limit", IDM_VIEW1, Enabled(), {}},
         {Kind::Item, L"#2 - 4x32 GPU Limit", IDM_VIEW2, Enabled(), {}},
         {Kind::Item, L"#3 - 32-bit BLA Limit", IDM_VIEW3, Enabled(), {}},
         {Kind::Item, L"#4 - 32-bit Scaled Limit", IDM_VIEW4, Enabled(), {}},
         {Kind::Item, L"#5 - 32-bit Scaled Limit, 4xAA", IDM_VIEW5, Enabled(), {}},
         {Kind::Item, L"#6 - Scale float with pixellation", IDM_VIEW6, Enabled(), {}},
         {Kind::Item, L"#7 - Scaled float limit with square", IDM_VIEW7, Enabled(), {}},
         {Kind::Item, L"#8 - ~10^700 or so, 0.5b iterations", IDM_VIEW8, Enabled(), {}},
         {Kind::Item, L"#9 - bug: scaled/BLA/32-bit failure", IDM_VIEW9, Enabled(), {}},
         {Kind::Item, L"#10 - ~10^130, ~2b iterations", IDM_VIEW10, Enabled(), {}},
         {Kind::Item, L"#11 - ~10^700 or so, ~3m iterations", IDM_VIEW11, Enabled(), {}},
         {Kind::Item, L"#12 - Nearby #14", IDM_VIEW12, Enabled(), {}},
         {Kind::Item, L"#13 - ~10^4000, ~100m iterations, 16xAA", IDM_VIEW13, Enabled(), {}},
         {Kind::Item, L"#14 - ~10^6000, ~2b iterations, 16xAA", IDM_VIEW14, Enabled(), {}},
         {Kind::Item, L"#15 - ~10^140, high period", IDM_VIEW15, Enabled(), {}},
         {Kind::Item, L"#16 - LAv2 test spot 1 (quick)", IDM_VIEW16, Enabled(), {}},
         {Kind::Item, L"#17 - LAv2 test spot 2 (quick)", IDM_VIEW17, Enabled(), {}},
         {Kind::Item, L"#18 - #5 with point + magnification", IDM_VIEW18, Enabled(), {}},
         {Kind::Item, L"#19 - LAv2 test spot 3 (quick)", IDM_VIEW19, Enabled(), {}},
         {Kind::Item, L"#20 - ~10 minutes ref orbit, 50x10^9 iters", IDM_VIEW20, Enabled(), {}},
         {Kind::Item, L"#21 - ~10^11000, 2b iterations", IDM_VIEW21, Enabled(), {}},
         {Kind::Item, L"#22 - high period", IDM_VIEW22, Enabled(), {}},
         {Kind::Item, L"#23 - high period, 50b iterations", IDM_VIEW23, Enabled(), {}},
         {Kind::Item, L"#24", IDM_VIEW24, Enabled(), {}},
         {Kind::Item, L"#25 - Claude - low period, 32-bit, hard GPU", IDM_VIEW25, Enabled(), {}},
         {Kind::Item, L"#26 - low period, 1x32 busted, 1x64 OK, hard GPU", IDM_VIEW26, Enabled(), {}},
         {Kind::Item, L"#27", IDM_VIEW27, Enabled(), {}},
         {Kind::Item, L"#28", IDM_VIEW28, Enabled(), {}},
         {Kind::Item, L"#29 - Fast HDRx32 broke, HDRx64 works", IDM_VIEW29, Enabled(), {}},
         {Kind::Item, L"#30 - 1e100000 - low period", IDM_VIEW30, Enabled(), {}},
     }},
    {Kind::Item, L"Recalculate, Reuse Reference", IDM_SQUAREVIEW, Enabled(), {}},
    {Kind::Separator, L"", 0, 0, {}},
    {Kind::Item, L"Toggle Repainting", IDM_REPAINTING, Enabled(), {}},
    {Kind::Item, L"Toggle Window Size", IDM_WINDOWED, Enabled(), {}},
    {Kind::Item, L"Toggle Window Size (Square)", IDM_WINDOWED_SQ, Enabled(), {}},
    {Kind::Item, L"Minimize Window", IDM_MINIMIZE, Enabled(), {}},
    {Kind::Separator, L"", 0, 0, {}},
    {Kind::Popup,
     L"GPU Antialiasing",
     0,
     0,
     {
         {Kind::Item, L"1x (fast)", IDM_GPUANTIALIASING_1X, Enabled(), {}},
         {Kind::Item, L"4x", IDM_GPUANTIALIASING_4X, Enabled(), {}},
         {Kind::Item, L"9x", IDM_GPUANTIALIASING_9X, Enabled(), {}},
         {Kind::Item, L"16x (better quality)", IDM_GPUANTIALIASING_16X, Enabled(), {}},
     }},
    {Kind::Popup,
     L"Choose Render Algorithm",
     0,
     0,
     {
         {Kind::Item, L"Help", IDM_HELP_ALG, Enabled(), {}},
         {Kind::Item, L"Auto (Default)", IDM_ALG_AUTO, Enabled(), {}},
         {Kind::Popup,
          L"LA Parameters",
          0,
          0,
          {
              {Kind::Item, L"Multithreaded (Default)", IDM_LA_MULTITHREADED, Enabled(), {}},
              {Kind::Item, L"Single Threaded", IDM_LA_SINGLETHREADED, Enabled(), {}},
              {Kind::Separator, L"", 0, 0, {}},
              {Kind::Item, L"Max Accuracy (Default)", IDM_LA_SETTINGS_1, Enabled(), {}},
              {Kind::Item, L"Max Performance (Accuracy Loss)", IDM_LA_SETTINGS_2, Enabled(), {}},
              {Kind::Item, L"Min Memory", IDM_LA_SETTINGS_3, Enabled(), {}},
          }},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Popup,
          L"CPU-Only",
          0,
          0,
          {
              {Kind::Item, L"Very High Precision CPU", IDM_ALG_CPU_HIGH, Enabled(), {}},
              {Kind::Separator, L"", 0, 0, {}},
              {Kind::Item, L"1x64 CPU", IDM_ALG_CPU_1_64, Enabled(), {}},
              {Kind::Item, L"HDRx32 CPU", IDM_ALG_CPU_1_32_HDR, Enabled(), {}},
              {Kind::Item, L"HDRx64 CPU", IDM_ALG_CPU_1_64_HDR, Enabled(), {}},
              {Kind::Separator, L"", 0, 0, {}},
              {Kind::Item, L"1x64 CPU - Perturbation BLA", IDM_ALG_CPU_1_64_PERTURB_BLA, Enabled(), {}},
              {Kind::Item,
               L"HDRx32 CPU - Perturbation BLA",
               IDM_ALG_CPU_1_32_PERTURB_BLA_HDR,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx64 CPU - Perturbation BLA",
               IDM_ALG_CPU_1_64_PERTURB_BLA_HDR,
               Enabled(),
               {}},
              {Kind::Separator, L"", 0, 0, {}},
              {Kind::Item,
               L"HDRx32 CPU - Perturbation LAv2",
               IDM_ALG_CPU_1_32_PERTURB_BLAV2_HDR,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx64 CPU - Perturbation LAv2",
               IDM_ALG_CPU_1_64_PERTURB_BLAV2_HDR,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx32 RC CPU - Perturbation LAv2",
               IDM_ALG_CPU_1_32_PERTURB_RC_BLAV2_HDR,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx64 RC CPU - Perturbation LAv2",
               IDM_ALG_CPU_1_64_PERTURB_RC_BLAV2_HDR,
               Enabled(),
               {}},
          }},
         {Kind::Popup,
          L"Low-Zoom Depth",
          0,
          0,
          {
              {Kind::Popup,
               L"Iteration Precision",
               0,
               0,
               {
                   {Kind::Item, L"4x (fast)", IDM_ITERATIONPRECISION_4X, Enabled(), {}},
                   {Kind::Item, L"3x", IDM_ITERATIONPRECISION_3X, Enabled(), {}},
                   {Kind::Item, L"2x", IDM_ITERATIONPRECISION_2X, Enabled(), {}},
                   {Kind::Item, L"1x (better quality)", IDM_ITERATIONPRECISION_1X, Enabled(), {}},
               }},
              {Kind::Separator, L"", 0, 0, {}},
              {Kind::Item, L"1x32 GPU", IDM_ALG_GPU_1_32, Enabled(), {}},
              {Kind::Item, L"2x32 GPU", IDM_ALG_GPU_2_32, Enabled(), {}},
              {Kind::Item, L"4x32 GPU", IDM_ALG_GPU_4_32, Enabled(), {}},
              {Kind::Item, L"1x64 GPU", IDM_ALG_GPU_1_64, Enabled(), {}},
              {Kind::Item, L"2x64 GPU", IDM_ALG_GPU_2_64, Enabled(), {}},
              {Kind::Item, L"4x64 GPU", IDM_ALG_GPU_4_64, Enabled(), {}},
              {Kind::Item, L"HDRx32 GPU", IDM_ALG_GPU_2X32_HDR, Enabled(), {}},
          }},
         {Kind::Popup,
          L"Scaled",
          0,
          0,
          {
              {Kind::Item,
               L"1x32 GPU - Perturbation Scaled",
               IDM_ALG_GPU_1_32_PERTURB_SCALED,
               Enabled(),
               {}},
              {Kind::Item,
               L"2x32 GPU - Perturbation Scaled (broken)",
               IDM_ALG_GPU_2_32_PERTURB_SCALED,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx32 GPU - Perturbation Scaled",
               IDM_ALG_GPU_HDR_32_PERTURB_SCALED,
               Enabled(),
               {}},
          }},
         {Kind::Popup,
          L"Bilinear Approximation V1",
          0,
          0,
          {
              {Kind::Item, L"1x64 GPU - Perturbation BLA", IDM_ALG_GPU_1_64_PERTURB_BLA, Enabled(), {}},
              {Kind::Item,
               L"HDRx32 GPU - Perturbation BLA",
               IDM_ALG_GPU_HDR_32_PERTURB_BLA,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx64 GPU - Perturbation BLA",
               IDM_ALG_GPU_HDR_64_PERTURB_BLA,
               Enabled(),
               {}},
          }},
         {Kind::Popup,
          L"LA Only (for testing)",
          0,
          0,
          {
              {Kind::Item,
               L"1x32 GPU - LAv2 - LA only",
               IDM_ALG_GPU_1_32_PERTURB_LAV2_LAO,
               Enabled(),
               {}},
              {Kind::Item,
               L"2x32 GPU - LAv2 - LA only",
               IDM_ALG_GPU_2_32_PERTURB_LAV2_LAO,
               Enabled(),
               {}},
              {Kind::Item,
               L"1x64 GPU - LAv2 - LA only",
               IDM_ALG_GPU_1_64_PERTURB_LAV2_LAO,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx32 GPU - LAv2 - LA only",
               IDM_ALG_GPU_HDR_32_PERTURB_LAV2_LAO,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx2x32 GPU - LAv2 - LA only",
               IDM_ALG_GPU_HDR_2X32_PERTURB_LAV2_LAO,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx64 GPU - LAv2 - LA only",
               IDM_ALG_GPU_HDR_64_PERTURB_LAV2_LAO,
               Enabled(),
               {}},
          }},
         {Kind::Popup,
          L"Perturbation Only",
          0,
          0,
          {
              {Kind::Item, L"1x32 GPU - Perturb only", IDM_ALG_GPU_1_32_PERTURB_LAV2_PO, Enabled(), {}},
              {Kind::Item, L"2x32 GPU - Perturb only", IDM_ALG_GPU_2_32_PERTURB_LAV2_PO, Enabled(), {}},
              {Kind::Item, L"1x64 GPU - Perturb only", IDM_ALG_GPU_1_64_PERTURB_LAV2_PO, Enabled(), {}},
              {Kind::Item,
               L"HDRx32 GPU - Perturb only",
               IDM_ALG_GPU_HDR_32_PERTURB_LAV2_PO,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx2x32 GPU - Perturb only",
               IDM_ALG_GPU_HDR_2X32_PERTURB_LAV2_PO,
               Enabled(),
               {}},
              {Kind::Item,
               L"HDRx64 GPU - Perturb only",
               IDM_ALG_GPU_HDR_64_PERTURB_LAV2_PO,
               Enabled(),
               {}},
          }},
         {Kind::Popup,
          L"Reference Compression",
          0,
          0,
          {
              {Kind::Item, L"1x32 GPU - RC LAv2", IDM_ALG_GPU_1_32_PERTURB_RC_LAV2, Enabled(), {}},
              {Kind::Item, L"2x32 GPU - RC LAv2", IDM_ALG_GPU_2_32_PERTURB_RC_LAV2, Enabled(), {}},
              {Kind::Item, L"1x64 GPU - RC LAv2", IDM_ALG_GPU_1_64_PERTURB_RC_LAV2, Enabled(), {}},
              {Kind::Item, L"HDRx32 GPU - RC LAv2", IDM_ALG_GPU_HDR_32_PERTURB_RC_LAV2, Enabled(), {}},
              {Kind::Item,
               L"HDRx2x32 GPU - RC LAv2",
               IDM_ALG_GPU_HDR_2X32_PERTURB_RC_LAV2,
               Enabled(),
               {}},
              {Kind::Item, L"HDRx64 GPU - RC LAv2", IDM_ALG_GPU_HDR_64_PERTURB_RC_LAV2, Enabled(), {}},
              {Kind::Popup,
               L"Perturbation Only",
               0,
               0,
               {
                   {Kind::Item,
                    L"1x32 GPU - RC Perturb Only",
                    IDM_ALG_GPU_1_32_PERTURB_RC_LAV2_PO,
                    Enabled(),
                    {}},
                   {Kind::Item,
                    L"2x32 GPU - RC Perturb Only",
                    IDM_ALG_GPU_2_32_PERTURB_RC_LAV2_PO,
                    Enabled(),
                    {}},
                   {Kind::Item,
                    L"1x64 GPU - RC Perturb Only",
                    IDM_ALG_GPU_1_64_PERTURB_RC_LAV2_PO,
                    Enabled(),
                    {}},
                   {Kind::Item,
                    L"HDRx32 GPU - RC Perturb Only",
                    IDM_ALG_GPU_HDR_32_PERTURB_RC_LAV2_PO,
                    Enabled(),
                    {}},
                   {Kind::Item,
                    L"HDRx2x32 GPU - RC Perturb Only",
                    IDM_ALG_GPU_HDR_2X32_PERTURB_RC_LAV2_PO,
                    Enabled(),
                    {}},
                   {Kind::Item,
                    L"HDRx64 GPU - RC Perturb Only",
                    IDM_ALG_GPU_HDR_64_PERTURB_RC_LAV2_PO,
                    Enabled(),
                    {}},
               }},
              {Kind::Popup,
               L"LA Only",
               0,
               0,
               {
                   {Kind::Item,
                    L"1x32 GPU - RC LAv2",
                    IDM_ALG_GPU_1_32_PERTURB_RC_LAV2_LAO,
                    Enabled(),
                    {}},
                   {Kind::Item,
                    L"2x32 GPU - RC LAv2",
                    IDM_ALG_GPU_2_32_PERTURB_RC_LAV2_LAO,
                    Enabled(),
                    {}},
                   {Kind::Item,
                    L"1x64 GPU - RC LAv2",
                    IDM_ALG_GPU_1_64_PERTURB_RC_LAV2_LAO,
                    Enabled(),
                    {}},
                   {Kind::Item,
                    L"HDRx32 GPU - RC LAv2",
                    IDM_ALG_GPU_HDR_32_PERTURB_RC_LAV2_LAO,
                    Enabled(),
                    {}},
                   {Kind::Item,
                    L"HDRx2x32 GPU - RC LAv2",
                    IDM_ALG_GPU_HDR_2X32_PERTURB_RC_LAV2_LAO,
                    Enabled(),
                    {}},
                   {Kind::Item,
                    L"HDRx64 GPU - RC LAv2",
                    IDM_ALG_GPU_HDR_64_PERTURB_RC_LAV2_LAO,
                    Enabled(),
                    {}},
               }},
          }},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"1x32 GPU - LAv2", IDM_ALG_GPU_1_32_PERTURB_LAV2, Enabled(), {}},
         {Kind::Item, L"2x32 GPU - LAv2", IDM_ALG_GPU_2_32_PERTURB_LAV2, Enabled(), {}},
         {Kind::Item, L"1x64 GPU - LAv2", IDM_ALG_GPU_1_64_PERTURB_LAV2, Enabled(), {}},
         {Kind::Item, L"HDRx32 GPU - LAv2", IDM_ALG_GPU_HDR_32_PERTURB_LAV2, Enabled(), {}},
         {Kind::Item, L"HDRx2x32 GPU - LAv2", IDM_ALG_GPU_HDR_2X32_PERTURB_LAV2, Enabled(), {}},
         {Kind::Item, L"HDRx64 GPU - LAv2", IDM_ALG_GPU_HDR_64_PERTURB_LAV2, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Popup,
          L"Tests",
          0,
          0,
          {
              {Kind::Item, L"Run Basic Test (saves files in local dir)", IDM_BASICTEST, Enabled(), {}},
              {Kind::Item, L"Run View #27 test", IDM_TEST_27, Enabled(), {}},
          }},
     }},
    {Kind::Popup,
     L"Iterations",
     0,
     0,
     {
         {Kind::Item, L"De&fault Iterations", IDM_RESETITERATIONS, Enabled(), {}},
         {Kind::Item, L"+1.5x", IDM_INCREASEITERATIONS_1P5X, Enabled(), {}},
         {Kind::Item, L"+6x", IDM_INCREASEITERATIONS_6X, Enabled(), {}},
         {Kind::Item, L"+24x", IDM_INCREASEITERATIONS_24X, Enabled(), {}},
         {Kind::Item, L"&Decrease Iterations", IDM_DECREASEITERATIONS, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"32-Bit Iterations", IDM_32BIT_ITERATIONS, Enabled(), {}},
         {Kind::Item, L"64-Bit Iterations", IDM_64BIT_ITERATIONS, Enabled(), {}},
     }},
    {Kind::Popup,
     L"Perturbation",
     0,
     0,
     {
         {Kind::Item, L"Clear Perturbation References - All", IDM_PERTURB_CLEAR_ALL, Enabled(), {}},
         {Kind::Item, L"Clear Perturbation References - Med", IDM_PERTURB_CLEAR_MED, Enabled(), {}},
         {Kind::Item, L"Clear Perturbation References - High", IDM_PERTURB_CLEAR_HIGH, Enabled(), {}},
         {Kind::Item, L"Show Perturbation Results", IDM_PERTURB_RESULTS, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Auto (default)", IDM_PERTURBATION_AUTO, Enabled(), {}},
         {Kind::Item, L"Single Thread (ST)", IDM_PERTURBATION_SINGLETHREAD, Enabled(), {}},
         {Kind::Item, L"Multi Thread (MT)", IDM_PERTURBATION_MULTITHREAD, Enabled(), {}},
         {Kind::Item, L"ST + Periodicity", IDM_PERTURBATION_SINGLETHREAD_PERIODICITY, Enabled(), {}},
         {Kind::Item, L"MT2 + Periodicity", IDM_PERTURBATION_MULTITHREAD2_PERIODICITY, Enabled(), {}},
         {Kind::Item,
          L"MT2 + Periodicity + Perturb ST",
          IDM_PERTURBATION_MULTITHREAD2_PERIODICITY_PERTURB_MTHIGH_STMED,
          Enabled(),
          {}},
         {Kind::Item,
          L"MT2 + Periodicity + Perturb MT v1",
          IDM_PERTURBATION_MULTITHREAD2_PERIODICITY_PERTURB_MTHIGH_MTMED1,
          Enabled(),
          {}},
         {Kind::Item,
          L"MT2 + Periodicity + Perturb MT v2",
          IDM_PERTURBATION_MULTITHREAD2_PERIODICITY_PERTURB_MTHIGH_MTMED2,
          Enabled(),
          {}},
         {Kind::Item,
          L"MT2 + Periodicity + Perturb MT v3",
          IDM_PERTURBATION_MULTITHREAD2_PERIODICITY_PERTURB_MTHIGH_MTMED3,
          Enabled(),
          {}},
         {Kind::Item,
          L"MT2 + Periodicity + Perturb MT v4 (broken)",
          IDM_PERTURBATION_MULTITHREAD2_PERIODICITY_PERTURB_MTHIGH_MTMED4,
          Enabled(),
          {}},
         {Kind::Item, L"MT5 + Periodicity", IDM_PERTURBATION_MULTITHREAD5_PERIODICITY, Inactive(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"GPU-Accelerated (see README)", IDM_PERTURBATION_GPU, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Clear and Reload Reference Orbits", IDM_PERTURBATION_LOAD, Enabled(), {}},
         {Kind::Item, L"Save Reference Orbits", IDM_PERTURBATION_SAVE, Enabled(), {}},
     }},
    {Kind::Separator, L"", 0, 0, {}},
    {Kind::Popup,
     L"Palette Color Depth",
     0,
     0,
     {
         {Kind::Item, L"Basic", IDM_PALETTE_TYPE_0, Inactive(), {}},
         {Kind::Item, L"Default", IDM_PALETTE_TYPE_1, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Patriotic", IDM_PALETTE_TYPE_2, Enabled(), {}},
         {Kind::Item, L"Summer", IDM_PALETTE_TYPE_3, Enabled(), {}},
         {Kind::Item, L"Random", IDM_PALETTE_TYPE_4, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"&Create Random Palette", IDM_CREATENEWPALETTE, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"5-bit", IDM_PALETTE_5, Enabled(), {}},
         {Kind::Item, L"6-bit", IDM_PALETTE_6, Enabled(), {}},
         {Kind::Item, L"8-bit", IDM_PALETTE_8, Enabled(), {}},
         {Kind::Item, L"12-bit", IDM_PALETTE_12, Enabled(), {}},
         {Kind::Item, L"16-bit", IDM_PALETTE_16, Enabled(), {}},
         {Kind::Item, L"20-bit", IDM_PALETTE_20, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Pa&lette Rotation", IDM_PALETTEROTATE, Inactive(), {}},
     }},
    {Kind::Separator, L"", 0, 0, {}},
    {Kind::Popup,
     L"Memory Management",
     0,
     0,
     {
         {Kind::Item,
          L"Enable Auto-Save Orbit (delete when done, default)",
          IDM_PERTURB_AUTOSAVE_ON_DELETE,
          Enabled(),
          {}},
         {Kind::Item, L"Enable Auto-Save Orbit (keep files)", IDM_PERTURB_AUTOSAVE_ON, Enabled(), {}},
         {Kind::Item, L"Disable Auto-Save Orbit", IDM_PERTURB_AUTOSAVE_OFF, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Remove Memory Limits", IDM_MEMORY_LIMIT_0, Enabled(), {}},
         {Kind::Item, L"Leave max of (1/2*ram, 8GB) free (default)", IDM_MEMORY_LIMIT_1, Enabled(), {}},
     }},
    {Kind::Item, L"Show Rendering Details", IDM_CURPOS, Enabled(), {}},
    {Kind::Popup,
     L"Save",
     0,
     0,
     {
         {Kind::Item, L"Save Location...", IDM_SAVELOCATION, Enabled(), {}},
         {Kind::Item, L"Save High Res Bitmap", IDM_SAVEHIRESBMP, Enabled(), {}},
         {Kind::Item, L"Save Iterations as Text", IDM_SAVE_ITERS_TEXT, Enabled(), {}},
         {Kind::Item, L"Save Bitmap Ima&ge", IDM_SAVEBMP, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Save Reference Orbit as Text", IDM_SAVE_REFORBIT_TEXT, Enabled(), {}},
         {Kind::Item,
          L"Save Compressed Orbit as Text (simple)",
          IDM_SAVE_REFORBIT_TEXT_SIMPLE,
          Enabled(),
          {}},
         {Kind::Item, L"Save Compressed Orbit as Text (max)", IDM_SAVE_REFORBIT_TEXT_MAX, Enabled(), {}},
         {Kind::Item, L"Save Compressed Orbit (Imagina/max)", IDM_SAVE_REFORBIT_IMAG_MAX, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Benchmark (5x, full recalc)", IDM_BENCHMARK_FULL, Enabled(), {}},
         {Kind::Item, L"Benchmark (5x, intermediate only)", IDM_BENCHMARK_INT, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Diff Imagina Orbits (choose two)", IDM_DIFF_REFORBIT_IMAG_MAX, Enabled(), {}},
     }},
    {Kind::Popup,
     L"Load",
     0,
     0,
     {
         {Kind::Item, L"Load Location...", IDM_LOADLOCATION, Enabled(), {}},
         {Kind::Item, L"Enter Location", IDM_LOAD_ENTERLOCATION, Enabled(), {}},
         {Kind::Separator, L"", 0, 0, {}},
         {Kind::Item, L"Load Imagina Orbit (Match)...", IDM_LOAD_REFORBIT_IMAG_MAX, Enabled(), {}},
         {Kind::Item,
          L"Load Imagina Orbit (Use Saved)...",
          IDM_LOAD_REFORBIT_IMAG_MAX_SAVED,
          Enabled(),
          {}},
     }},
    {Kind::Separator, L"", 0, 0, {}},
    {Kind::Item, L"E&xit", IDM_EXIT, Enabled(), {}},
};