move -Force .\FractalSaver.vcxproj            .\FractalSaver\FractalSaver.vcxproj
move -Force .\Fractals.vcxproj                .\FractalShark\Fractals.vcxproj
move -Force .\FractalSharkGpuLib.vcxproj      .\FractalSharkGpuLib\FractalSharkGpuLib.vcxproj
move -Force .\FractalSharkLib.vcxproj         .\FractalSharkLib\FractalSharkLib.vcxproj
move -Force .\FractalTray.vcxproj             .\FractalTray\FractalTray.vcxproj
move -Force .\HpSharkFloatLib.vcxproj         .\HpSharkFloatLib\HpSharkFloatLib.vcxproj
move -Force .\HpSharkFloatTest.vcxproj        .\HpSharkFloatTest\HpSharkFloatTest.vcxproj
move -Force .\HpSharkFloatTestLib.vcxproj     .\HpSharkFloatTestLib\HpSharkFloatTestLib.vcxproj
move -Force .\HpSharkInstantiate.vcxproj      .\HpSharkInstantiate\HpSharkInstantiate.vcxproj
move -Force .\FractalShark.CudaDefaults.props .\FractalShark
move -Force .\FractalShark.MsvcDefaults.props .\FractalShark
move -Force .\build.yml                       .\.github\workflows
move -Force .\CudaAuto.props                  .\FractalShark
move -Force .\Directory.FractalShark.props    .\FractalShark
