//
// MenuTreeDef.h - canonical menu definition.
//
// This header is INCLUDED INSIDE a function body and qualifies each menu
// factory and type with the FractalShark namespace. It defines a single
// `static const FractalShark::Node menu[] = {...}` array describing the
// application's context menu.
//
// Important detail: popup children must have *stable storage*.
// Braced lists like `{ Item(...), ... }` produce temporary arrays, and
// std::initializer_list does not own that memory. If we stored an
// initializer_list inside a Node and recursed later, we could end up
// iterating dangling memory.
//
// To keep the "giant definition" style while making kids stable, each
// Popup is created via a small wrapper (FS_POPUP / FS_POPUP0) that:
//   1) hoists the children into a hidden `static const Node _kids[]` array,
//   2) passes `std::span{_kids}` into Popup(...),
//   3) returns a normal Node that simply *views* those children.
//
// Result: `menu[]` stays readable and static, and every submenu's children
// live for the entire program lifetime, so recursive menu walking is safe.
//

#include <span>

#define FS_POPUP(label, enableRule, adornGroup, ...)                                                    \
    []() -> ::FractalShark::Node {                                                                      \
        static const ::FractalShark::Node _kids[] = {__VA_ARGS__};                                      \
        return ::FractalShark::Popup(                                                                   \
            label, std::span<const ::FractalShark::Node>{_kids}, enableRule, adornGroup);               \
    }()

#define FS_POPUP0(label, ...)                                                                           \
    FS_POPUP(label, ::FractalShark::Rule::Always, ::FractalShark::RadioGroup::None, __VA_ARGS__)

// -----------------------------------------------------------------------------
// Menu definition (structure preserved; only Popup(...) replaced)
// -----------------------------------------------------------------------------

static const ::FractalShark::Node menu[] = {
    ::FractalShark::Item(L"Show Help", ::FractalShark::FractalCommand::ShowHotkeys),
    ::FractalShark::Sep(),

    FS_POPUP0(
        L"Navigate",
        ::FractalShark::Item(L"Back", ::FractalShark::FractalCommand::Back),
        ::FractalShark::Sep(),
        ::FractalShark::Item(L"Center View Here", ::FractalShark::FractalCommand::CenterView),
        ::FractalShark::Item(L"Zoom In Here", ::FractalShark::FractalCommand::ZoomIn),
        ::FractalShark::Item(L"Zoom Out", ::FractalShark::FractalCommand::ZoomOut),
        ::FractalShark::Sep(),
        ::FractalShark::Item(L"Autozoom Feature With Checkpoint Save (a)",
                             ::FractalShark::FractalCommand::AutoZoomFeatureWithCheckpointSave),
        ::FractalShark::Item(L"Autozoom Feature Without Checkpoint Save (A)",
                             ::FractalShark::FractalCommand::AutoZoomFeatureWithoutCheckpointSave),
        ::FractalShark::Item(L"Autozoom Max", ::FractalShark::FractalCommand::AutoZoomMax),
        ::FractalShark::Item(L"Autozoom Filament Tip - heuristic, not that great (S)",
                             ::FractalShark::FractalCommand::AutoZoomFilament),
        ::FractalShark::Sep(),
        FS_POPUP0(
            L"Feature Finder",
            ::FractalShark::Item(L"Direct (n)", ::FractalShark::FractalCommand::FeatureFinderDirect),
            ::FractalShark::Item(L"DirectScan (N)",
                                 ::FractalShark::FractalCommand::FeatureFinderDirectScan),
            ::FractalShark::Item(L"PT (m)", ::FractalShark::FractalCommand::FeatureFinderPt),
            ::FractalShark::Item(L"PTScan (M)", ::FractalShark::FractalCommand::FeatureFinderPtScan),
            ::FractalShark::Item(L"LA (,)", ::FractalShark::FractalCommand::FeatureFinderLa),
            ::FractalShark::Item(L"LAScan (<)", ::FractalShark::FractalCommand::FeatureFinderLaScan),
            ::FractalShark::Sep(),
            ::FractalShark::Item(L"Zoom to Found Feature (.)",
                                 ::FractalShark::FractalCommand::FeatureFinderZoom),
            ::FractalShark::Item(L"Resume NR Refinement",
                                 ::FractalShark::FractalCommand::FeatureFinderResume,
                                 ::FractalShark::Rule::EnableIfNRCheckpointExists),
            ::FractalShark::Item(L"Clear All Found Features (>)",
                                 ::FractalShark::FractalCommand::FeatureFinderClear),
            ::FractalShark::Sep(),
            ::FractalShark::Radio(L"NR Inner Loop: GPU",
                                  ::FractalShark::FractalCommand::NrInnerLoopGpu,
                                  ::FractalShark::RadioGroup::NRInnerLoopBackend,
                                  ::FractalShark::Rule::EnableIfGpuActive),
            ::FractalShark::Radio(L"NR Inner Loop: CPU MT",
                                  ::FractalShark::FractalCommand::NrInnerLoopCpu,
                                  ::FractalShark::RadioGroup::NRInnerLoopBackend),
            ::FractalShark::Radio(L"NR Inner Loop: CPU ST",
                                  ::FractalShark::FractalCommand::NrInnerLoopCpuSt,
                                  ::FractalShark::RadioGroup::NRInnerLoopBackend))),
    FS_POPUP0(
        L"Built-In Views",
        ::FractalShark::Item(L"Help", ::FractalShark::FractalCommand::ViewsHelp),
        ::FractalShark::Sep(),
        ::FractalShark::Item(L"&Standard View", ::FractalShark::FractalCommand::StandardView),
        ::FractalShark::Item(L"#1 - 4x64 GPU Limit", ::FractalShark::FractalCommand::View1),
        ::FractalShark::Item(L"#2 - 4x32 GPU Limit", ::FractalShark::FractalCommand::View2),
        ::FractalShark::Item(L"#3 - 32-bit BLA Limit", ::FractalShark::FractalCommand::View3),
        ::FractalShark::Item(L"#4 - 32-bit Scaled Limit", ::FractalShark::FractalCommand::View4),
        ::FractalShark::Item(L"#5 - 32-bit Scaled Limit, 4xAA", ::FractalShark::FractalCommand::View5),
        ::FractalShark::Item(L"#6 - Scale float with pixellation",
                             ::FractalShark::FractalCommand::View6),
        ::FractalShark::Item(L"#7 - Scaled float limit with square",
                             ::FractalShark::FractalCommand::View7),
        ::FractalShark::Item(L"#8 - ~10^700 or so, 0.5b iterations",
                             ::FractalShark::FractalCommand::View8),
        ::FractalShark::Item(L"#9 - bug: scaled/BLA/32-bit failure",
                             ::FractalShark::FractalCommand::View9),
        ::FractalShark::Item(L"#10 - ~10^130, ~2b iterations", ::FractalShark::FractalCommand::View10),
        ::FractalShark::Item(L"#11 - ~10^700 or so, ~3m iterations",
                             ::FractalShark::FractalCommand::View11),
        ::FractalShark::Item(L"#12 - Nearby #14", ::FractalShark::FractalCommand::View12),
        ::FractalShark::Item(L"#13 - ~10^4000, ~100m iterations, 16xAA",
                             ::FractalShark::FractalCommand::View13),
        ::FractalShark::Item(L"#14 - ~10^6000, ~2b iterations, 16xAA",
                             ::FractalShark::FractalCommand::View14),
        ::FractalShark::Item(L"#15 - ~10^140, high period", ::FractalShark::FractalCommand::View15),
        ::FractalShark::Item(L"#16 - LAv2 test spot 1 (quick)", ::FractalShark::FractalCommand::View16),
        ::FractalShark::Item(L"#17 - LAv2 test spot 2 (quick)", ::FractalShark::FractalCommand::View17),
        ::FractalShark::Item(L"#18 - #5 with point + magnification",
                             ::FractalShark::FractalCommand::View18),
        ::FractalShark::Item(L"#19 - LAv2 test spot 3 (quick)", ::FractalShark::FractalCommand::View19),
        ::FractalShark::Item(L"#20 - ~10 minutes ref orbit, 50x10^9 iters",
                             ::FractalShark::FractalCommand::View20),
        ::FractalShark::Item(L"#21 - ~10^11000, 2b iterations", ::FractalShark::FractalCommand::View21),
        ::FractalShark::Item(L"#22 - high period", ::FractalShark::FractalCommand::View22),
        ::FractalShark::Item(L"#23 - high period, 50b iterations",
                             ::FractalShark::FractalCommand::View23),
        ::FractalShark::Item(L"#24", ::FractalShark::FractalCommand::View24),
        ::FractalShark::Item(L"#25 - Claude - low period, 32-bit, hard GPU",
                             ::FractalShark::FractalCommand::View25),
        ::FractalShark::Item(L"#26 - low period, 1x32 busted, 1x64 OK, hard GPU",
                             ::FractalShark::FractalCommand::View26),
        ::FractalShark::Item(L"#27", ::FractalShark::FractalCommand::View27),
        ::FractalShark::Item(L"#28", ::FractalShark::FractalCommand::View28),
        ::FractalShark::Item(L"#29 - Fast HDRx32 broke, HDRx64 works",
                             ::FractalShark::FractalCommand::View29),
        ::FractalShark::Item(L"#30 - 1e114514 - low period (70s rtx5090 reforbit)",
                             ::FractalShark::FractalCommand::View30),
        ::FractalShark::Item(L"#31 - 1e715 - feature finder test",
                             ::FractalShark::FractalCommand::View31),
        ::FractalShark::Item(L"#32 - 1e244240 - period 22,680,804",
                             ::FractalShark::FractalCommand::View32),
        ::FractalShark::Item(L"#33 - 1e325221 - period 22,680,804",
                             ::FractalShark::FractalCommand::View33),
        ::FractalShark::Item(L"#34 - 1e650452 - period 399,289,978",
                             ::FractalShark::FractalCommand::View34)),

    ::FractalShark::Item(L"Recalculate, Reuse Reference", ::FractalShark::FractalCommand::SquareView),
    ::FractalShark::Sep(),

    // Repainting reflects persistent renderer state. Window-size entries are
    // actions: both switch between fullscreen and a differently sized window.
    ::FractalShark::Toggle(L"Toggle Repainting", ::FractalShark::FractalCommand::Repainting),
    ::FractalShark::Item(L"Toggle Window Size", ::FractalShark::FractalCommand::Windowed),
    ::FractalShark::Item(L"Toggle Window Size (Square)", ::FractalShark::FractalCommand::WindowedSq),

    ::FractalShark::Item(L"Minimize Window", ::FractalShark::FractalCommand::Minimize),
    ::FractalShark::Sep(),

    FS_POPUP(L"Antialiasing",
             ::FractalShark::Rule::Always,
             /*adornment*/ ::FractalShark::RadioGroup::GpuAntialiasing,
             ::FractalShark::Radio(L"1x (fast)",
                                   ::FractalShark::FractalCommand::GpuAntialiasing1x,
                                   ::FractalShark::RadioGroup::GpuAntialiasing),
             ::FractalShark::Radio(L"4x",
                                   ::FractalShark::FractalCommand::GpuAntialiasing4x,
                                   ::FractalShark::RadioGroup::GpuAntialiasing),
             ::FractalShark::Radio(L"9x",
                                   ::FractalShark::FractalCommand::GpuAntialiasing9x,
                                   ::FractalShark::RadioGroup::GpuAntialiasing),
             ::FractalShark::Radio(L"16x (better quality)",
                                   ::FractalShark::FractalCommand::GpuAntialiasing16x,
                                   ::FractalShark::RadioGroup::GpuAntialiasing)),

    FS_POPUP(L"Choose Render Algorithm",
             ::FractalShark::Rule::Always,
             /*adornment*/ ::FractalShark::RadioGroup::RenderAlgorithm,

             ::FractalShark::Item(L"Help", ::FractalShark::FractalCommand::HelpAlg),

             // All algorithms are one big mutually-exclusive group
             ::FractalShark::Radio(L"Auto (Default)",
                                   ::FractalShark::FractalCommand::AlgAuto,
                                   ::FractalShark::RadioGroup::RenderAlgorithm),

             FS_POPUP0(L"LA Parameters",
                       ::FractalShark::Radio(L"Multithreaded (Default)",
                                             ::FractalShark::FractalCommand::LaMultithreaded,
                                             ::FractalShark::RadioGroup::LaThreading),
                       ::FractalShark::Radio(L"Single Threaded",
                                             ::FractalShark::FractalCommand::LaSinglethreaded,
                                             ::FractalShark::RadioGroup::LaThreading),
                       ::FractalShark::Sep(),
                       ::FractalShark::Item(L"Max Accuracy (Default)",
                                            ::FractalShark::FractalCommand::LaSettings1),
                       ::FractalShark::Item(L"Max Performance (Accuracy Loss)",
                                            ::FractalShark::FractalCommand::LaSettings2),
                       ::FractalShark::Item(L"Min Memory", ::FractalShark::FractalCommand::LaSettings3)),

             ::FractalShark::Sep(),

             FS_POPUP0(L"CPU-Only",
                       ::FractalShark::Radio(L"Very High Precision CPU",
                                             ::FractalShark::FractalCommand::AlgCpuHigh,
                                             ::FractalShark::RadioGroup::RenderAlgorithm),
                       ::FractalShark::Sep(),
                       ::FractalShark::Radio(L"1x64 CPU",
                                             ::FractalShark::FractalCommand::AlgCpu1x64,
                                             ::FractalShark::RadioGroup::RenderAlgorithm),
                       ::FractalShark::Radio(L"HDRx32 CPU",
                                             ::FractalShark::FractalCommand::AlgCpu1x32Hdr,
                                             ::FractalShark::RadioGroup::RenderAlgorithm),
                       ::FractalShark::Radio(L"HDRx64 CPU",
                                             ::FractalShark::FractalCommand::AlgCpu1x64Hdr,
                                             ::FractalShark::RadioGroup::RenderAlgorithm),
                       ::FractalShark::Sep(),
                       ::FractalShark::Radio(L"1x64 CPU - Perturbation BLA",
                                             ::FractalShark::FractalCommand::AlgCpu1x64PerturbBla,
                                             ::FractalShark::RadioGroup::RenderAlgorithm),
                       ::FractalShark::Radio(L"HDRx32 CPU - Perturbation BLA",
                                             ::FractalShark::FractalCommand::AlgCpu1x32PerturbBlaHdr,
                                             ::FractalShark::RadioGroup::RenderAlgorithm),
                       ::FractalShark::Radio(L"HDRx64 CPU - Perturbation BLA",
                                             ::FractalShark::FractalCommand::AlgCpu1x64PerturbBlaHdr,
                                             ::FractalShark::RadioGroup::RenderAlgorithm),
                       ::FractalShark::Sep(),
                       ::FractalShark::Radio(L"HDRx32 CPU - Perturbation LAv2",
                                             ::FractalShark::FractalCommand::AlgCpu1x32PerturbBlav2Hdr,
                                             ::FractalShark::RadioGroup::RenderAlgorithm),
                       ::FractalShark::Radio(L"HDRx64 CPU - Perturbation LAv2",
                                             ::FractalShark::FractalCommand::AlgCpu1x64PerturbBlav2Hdr,
                                             ::FractalShark::RadioGroup::RenderAlgorithm),
                       ::FractalShark::Radio(L"HDRx32 RC CPU - Perturbation LAv2",
                                             ::FractalShark::FractalCommand::AlgCpu1x32PerturbRcBlav2Hdr,
                                             ::FractalShark::RadioGroup::RenderAlgorithm),
                       ::FractalShark::Radio(L"HDRx64 RC CPU - Perturbation LAv2",
                                             ::FractalShark::FractalCommand::AlgCpu1x64PerturbRcBlav2Hdr,
                                             ::FractalShark::RadioGroup::RenderAlgorithm)),

             FS_POPUP0(
                 L"Low-Zoom Depth",

                 FS_POPUP(L"Iteration Precision",
                          ::FractalShark::Rule::Always,
                          /*adornment*/ ::FractalShark::RadioGroup::IterationPrecision,
                          ::FractalShark::Radio(L"4x (fast)",
                                                ::FractalShark::FractalCommand::IterationPrecision4x,
                                                ::FractalShark::RadioGroup::IterationPrecision),
                          ::FractalShark::Radio(L"3x",
                                                ::FractalShark::FractalCommand::IterationPrecision3x,
                                                ::FractalShark::RadioGroup::IterationPrecision),
                          ::FractalShark::Radio(L"2x",
                                                ::FractalShark::FractalCommand::IterationPrecision2x,
                                                ::FractalShark::RadioGroup::IterationPrecision),
                          ::FractalShark::Radio(L"1x (better quality)",
                                                ::FractalShark::FractalCommand::IterationPrecision1x,
                                                ::FractalShark::RadioGroup::IterationPrecision)),

                 ::FractalShark::Sep(),

                 ::FractalShark::Radio(L"1x32 GPU",
                                       ::FractalShark::FractalCommand::AlgGpu1x32,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"2x32 GPU",
                                       ::FractalShark::FractalCommand::AlgGpu2x32,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"4x32 GPU",
                                       ::FractalShark::FractalCommand::AlgGpu4x32,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"1x64 GPU",
                                       ::FractalShark::FractalCommand::AlgGpu1x64,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"2x64 GPU",
                                       ::FractalShark::FractalCommand::AlgGpu2x64,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"4x64 GPU",
                                       ::FractalShark::FractalCommand::AlgGpu4x64,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"HDRx32 GPU",
                                       ::FractalShark::FractalCommand::AlgGpu2x32Hdr,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive)),

             FS_POPUP0(L"Scaled",
                       ::FractalShark::Radio(L"1x32 GPU - Perturbation Scaled",
                                             ::FractalShark::FractalCommand::AlgGpu1x32PerturbScaled,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"2x32 GPU - Perturbation Scaled (broken)",
                                             ::FractalShark::FractalCommand::AlgGpu2x32PerturbScaled,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"HDRx32 GPU - Perturbation Scaled",
                                             ::FractalShark::FractalCommand::AlgGpuHdr32PerturbScaled,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive)),

             FS_POPUP0(L"Bilinear Approximation V1",
                       ::FractalShark::Radio(L"1x64 GPU - Perturbation BLA",
                                             ::FractalShark::FractalCommand::AlgGpu1x64PerturbBla,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"HDRx32 GPU - Perturbation BLA",
                                             ::FractalShark::FractalCommand::AlgGpuHdr32PerturbBla,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"HDRx64 GPU - Perturbation BLA",
                                             ::FractalShark::FractalCommand::AlgGpuHdr64PerturbBla,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive)),

             FS_POPUP0(L"LA Only (for testing)",
                       ::FractalShark::Radio(L"1x32 GPU - LAv2 - LA only",
                                             ::FractalShark::FractalCommand::AlgGpu1x32PerturbLav2Lao,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"2x32 GPU - LAv2 - LA only",
                                             ::FractalShark::FractalCommand::AlgGpu2x32PerturbLav2Lao,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"1x64 GPU - LAv2 - LA only",
                                             ::FractalShark::FractalCommand::AlgGpu1x64PerturbLav2Lao,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"HDRx32 GPU - LAv2 - LA only",
                                             ::FractalShark::FractalCommand::AlgGpuHdr32PerturbLav2Lao,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"HDRx2x32 GPU - LAv2 - LA only",
                                             ::FractalShark::FractalCommand::AlgGpuHdr2x32PerturbLav2Lao,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"HDRx64 GPU - LAv2 - LA only",
                                             ::FractalShark::FractalCommand::AlgGpuHdr64PerturbLav2Lao,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive)),

             FS_POPUP0(L"Perturbation Only",
                       ::FractalShark::Radio(L"1x32 GPU - Perturb only",
                                             ::FractalShark::FractalCommand::AlgGpu1x32PerturbLav2Po,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"2x32 GPU - Perturb only",
                                             ::FractalShark::FractalCommand::AlgGpu2x32PerturbLav2Po,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"1x64 GPU - Perturb only",
                                             ::FractalShark::FractalCommand::AlgGpu1x64PerturbLav2Po,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"HDRx32 GPU - Perturb only",
                                             ::FractalShark::FractalCommand::AlgGpuHdr32PerturbLav2Po,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"HDRx2x32 GPU - Perturb only",
                                             ::FractalShark::FractalCommand::AlgGpuHdr2x32PerturbLav2Po,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive),
                       ::FractalShark::Radio(L"HDRx64 GPU - Perturb only",
                                             ::FractalShark::FractalCommand::AlgGpuHdr64PerturbLav2Po,
                                             ::FractalShark::RadioGroup::RenderAlgorithm,
                                             ::FractalShark::Rule::EnableIfGpuActive)),

             FS_POPUP0(
                 L"Reference Compression",

                 ::FractalShark::Radio(L"1x32 GPU - RC LAv2",
                                       ::FractalShark::FractalCommand::AlgGpu1x32PerturbRcLav2,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"2x32 GPU - RC LAv2",
                                       ::FractalShark::FractalCommand::AlgGpu2x32PerturbRcLav2,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"1x64 GPU - RC LAv2",
                                       ::FractalShark::FractalCommand::AlgGpu1x64PerturbRcLav2,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"HDRx32 GPU - RC LAv2",
                                       ::FractalShark::FractalCommand::AlgGpuHdr32PerturbRcLav2,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"HDRx2x32 GPU - RC LAv2",
                                       ::FractalShark::FractalCommand::AlgGpuHdr2x32PerturbRcLav2,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),
                 ::FractalShark::Radio(L"HDRx64 GPU - RC LAv2",
                                       ::FractalShark::FractalCommand::AlgGpuHdr64PerturbRcLav2,
                                       ::FractalShark::RadioGroup::RenderAlgorithm,
                                       ::FractalShark::Rule::EnableIfGpuActive),

                 FS_POPUP0(
                     L"Perturbation Only",
                     ::FractalShark::Radio(L"1x32 GPU - RC Perturb Only",
                                           ::FractalShark::FractalCommand::AlgGpu1x32PerturbRcLav2Po,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive),
                     ::FractalShark::Radio(L"2x32 GPU - RC Perturb Only",
                                           ::FractalShark::FractalCommand::AlgGpu2x32PerturbRcLav2Po,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive),
                     ::FractalShark::Radio(L"1x64 GPU - RC Perturb Only",
                                           ::FractalShark::FractalCommand::AlgGpu1x64PerturbRcLav2Po,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive),
                     ::FractalShark::Radio(L"HDRx32 GPU - RC Perturb Only",
                                           ::FractalShark::FractalCommand::AlgGpuHdr32PerturbRcLav2Po,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive),
                     ::FractalShark::Radio(L"HDRx2x32 GPU - RC Perturb Only",
                                           ::FractalShark::FractalCommand::AlgGpuHdr2x32PerturbRcLav2Po,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive),
                     ::FractalShark::Radio(L"HDRx64 GPU - RC Perturb Only",
                                           ::FractalShark::FractalCommand::AlgGpuHdr64PerturbRcLav2Po,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive)),

                 FS_POPUP0(
                     L"LA Only",
                     ::FractalShark::Radio(L"1x32 GPU - RC LAv2",
                                           ::FractalShark::FractalCommand::AlgGpu1x32PerturbRcLav2Lao,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive),
                     ::FractalShark::Radio(L"2x32 GPU - RC LAv2",
                                           ::FractalShark::FractalCommand::AlgGpu2x32PerturbRcLav2Lao,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive),
                     ::FractalShark::Radio(L"1x64 GPU - RC LAv2",
                                           ::FractalShark::FractalCommand::AlgGpu1x64PerturbRcLav2Lao,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive),
                     ::FractalShark::Radio(L"HDRx32 GPU - RC LAv2",
                                           ::FractalShark::FractalCommand::AlgGpuHdr32PerturbRcLav2Lao,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive),
                     ::FractalShark::Radio(L"HDRx2x32 GPU - RC LAv2",
                                           ::FractalShark::FractalCommand::AlgGpuHdr2x32PerturbRcLav2Lao,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive),
                     ::FractalShark::Radio(L"HDRx64 GPU - RC LAv2",
                                           ::FractalShark::FractalCommand::AlgGpuHdr64PerturbRcLav2Lao,
                                           ::FractalShark::RadioGroup::RenderAlgorithm,
                                           ::FractalShark::Rule::EnableIfGpuActive))),

             ::FractalShark::Sep(),

             ::FractalShark::Radio(L"1x32 GPU - LAv2",
                                   ::FractalShark::FractalCommand::AlgGpu1x32PerturbLav2,
                                   ::FractalShark::RadioGroup::RenderAlgorithm,
                                   ::FractalShark::Rule::EnableIfGpuActive),
             ::FractalShark::Radio(L"2x32 GPU - LAv2",
                                   ::FractalShark::FractalCommand::AlgGpu2x32PerturbLav2,
                                   ::FractalShark::RadioGroup::RenderAlgorithm,
                                   ::FractalShark::Rule::EnableIfGpuActive),
             ::FractalShark::Radio(L"1x64 GPU - LAv2",
                                   ::FractalShark::FractalCommand::AlgGpu1x64PerturbLav2,
                                   ::FractalShark::RadioGroup::RenderAlgorithm,
                                   ::FractalShark::Rule::EnableIfGpuActive),
             ::FractalShark::Radio(L"HDRx32 GPU - LAv2",
                                   ::FractalShark::FractalCommand::AlgGpuHdr32PerturbLav2,
                                   ::FractalShark::RadioGroup::RenderAlgorithm,
                                   ::FractalShark::Rule::EnableIfGpuActive),
             ::FractalShark::Radio(L"HDRx2x32 GPU - LAv2",
                                   ::FractalShark::FractalCommand::AlgGpuHdr2x32PerturbLav2,
                                   ::FractalShark::RadioGroup::RenderAlgorithm,
                                   ::FractalShark::Rule::EnableIfGpuActive),
             ::FractalShark::Radio(L"HDRx64 GPU - LAv2",
                                   ::FractalShark::FractalCommand::AlgGpuHdr64PerturbLav2,
                                   ::FractalShark::RadioGroup::RenderAlgorithm,
                                   ::FractalShark::Rule::EnableIfGpuActive),

             ::FractalShark::Sep(),

             FS_POPUP0(
                 L"Tests",
                 ::FractalShark::Item(L"Run Basic Test (saves files in local dir)",
                                      ::FractalShark::FractalCommand::BasicTest),
                 ::FractalShark::Item(L"Run View #27 test", ::FractalShark::FractalCommand::Test27))),

    FS_POPUP0(
        L"Iterations",
        ::FractalShark::Item(L"De&fault Iterations", ::FractalShark::FractalCommand::ResetIterations),
        ::FractalShark::Item(L"+1.5x", ::FractalShark::FractalCommand::IncreaseIterations1p5x),
        ::FractalShark::Item(L"+6x", ::FractalShark::FractalCommand::IncreaseIterations6x),
        ::FractalShark::Item(L"+24x", ::FractalShark::FractalCommand::IncreaseIterations24x),
        ::FractalShark::Item(L"&Decrease Iterations",
                             ::FractalShark::FractalCommand::DecreaseIterations),
        ::FractalShark::Sep(),
        ::FractalShark::Radio(L"32-Bit Iterations",
                              ::FractalShark::FractalCommand::Iterations32Bit,
                              ::FractalShark::RadioGroup::IterationsWidth),
        ::FractalShark::Radio(L"64-Bit Iterations",
                              ::FractalShark::FractalCommand::Iterations64Bit,
                              ::FractalShark::RadioGroup::IterationsWidth)),

    FS_POPUP(L"Perturbation",
             ::FractalShark::Rule::Always,
             /*adornment*/ ::FractalShark::RadioGroup::PerturbationMode,

             ::FractalShark::Item(L"Clear Perturbation References - All",
                                  ::FractalShark::FractalCommand::PerturbClearAll),
             ::FractalShark::Item(L"Clear Perturbation References - Med",
                                  ::FractalShark::FractalCommand::PerturbClearMed),
             ::FractalShark::Item(L"Clear Perturbation References - High",
                                  ::FractalShark::FractalCommand::PerturbClearHigh),

             ::FractalShark::Sep(),

             ::FractalShark::Radio(L"Auto (default)",
                                   ::FractalShark::FractalCommand::PerturbationAuto,
                                   ::FractalShark::RadioGroup::PerturbationMode),
             ::FractalShark::Radio(L"Single Thread (ST)",
                                   ::FractalShark::FractalCommand::PerturbationSinglethread,
                                   ::FractalShark::RadioGroup::PerturbationMode),
             ::FractalShark::Radio(L"Multi Thread (MT)",
                                   ::FractalShark::FractalCommand::PerturbationMultithread,
                                   ::FractalShark::RadioGroup::PerturbationMode),
             ::FractalShark::Radio(L"ST + Periodicity",
                                   ::FractalShark::FractalCommand::PerturbationSinglethreadPeriodicity,
                                   ::FractalShark::RadioGroup::PerturbationMode),
             ::FractalShark::Radio(L"MT2 + Periodicity",
                                   ::FractalShark::FractalCommand::PerturbationMultithread2Periodicity,
                                   ::FractalShark::RadioGroup::PerturbationMode),
             ::FractalShark::Radio(
                 L"MT2 + Periodicity + Perturb ST",
                 ::FractalShark::FractalCommand::PerturbationMultithread2PeriodicityPerturbMthighStmed,
                 ::FractalShark::RadioGroup::PerturbationMode),
             ::FractalShark::Radio(
                 L"MT2 + Periodicity + Perturb MT v1",
                 ::FractalShark::FractalCommand::PerturbationMultithread2PeriodicityPerturbMthighMtmed1,
                 ::FractalShark::RadioGroup::PerturbationMode),
             ::FractalShark::Radio(
                 L"MT2 + Periodicity + Perturb MT v2",
                 ::FractalShark::FractalCommand::PerturbationMultithread2PeriodicityPerturbMthighMtmed2,
                 ::FractalShark::RadioGroup::PerturbationMode),
             ::FractalShark::Radio(
                 L"MT2 + Periodicity + Perturb MT v3",
                 ::FractalShark::FractalCommand::PerturbationMultithread2PeriodicityPerturbMthighMtmed3,
                 ::FractalShark::RadioGroup::PerturbationMode),
             ::FractalShark::Radio(
                 L"MT2 + Periodicity + Perturb MT v4 (broken)",
                 ::FractalShark::FractalCommand::PerturbationMultithread2PeriodicityPerturbMthighMtmed4,
                 ::FractalShark::RadioGroup::PerturbationMode),

             // Formerly Inactive(). Replace with a rule your IMenuState returns false for.
             ::FractalShark::Item(L"MT5 + Periodicity",
                                  ::FractalShark::FractalCommand::PerturbationMultithread5Periodicity,
                                  ::FractalShark::Rule::EnableIfPerturbationAvailable),

             // If this is also a mode selection you can convert it to Radio() in
             // ::FractalShark::RadioGroup::PerturbationMode.
             ::FractalShark::Radio(L"GPU-Accelerated Reference Orbit",
                                   ::FractalShark::FractalCommand::PerturbationGpu,
                                   ::FractalShark::RadioGroup::PerturbationMode,
                                   ::FractalShark::Rule::EnableIfGpuActive),

             ::FractalShark::Sep(),
             ::FractalShark::Item(L"Clear and Reload Reference Orbits",
                                  ::FractalShark::FractalCommand::PerturbationLoad),
             ::FractalShark::Item(L"Save Reference Orbits",
                                  ::FractalShark::FractalCommand::PerturbationSave)),

    ::FractalShark::Sep(),

    FS_POPUP(L"Palette Color Depth",
             ::FractalShark::Rule::Always,
             /*adornment*/ ::FractalShark::RadioGroup::PaletteBitDepth,

             ::FractalShark::Radio(L"Basic",
                                   ::FractalShark::FractalCommand::PaletteType0,
                                   ::FractalShark::RadioGroup::PaletteType),
             ::FractalShark::Radio(L"Default",
                                   ::FractalShark::FractalCommand::PaletteType1,
                                   ::FractalShark::RadioGroup::PaletteType),

             ::FractalShark::Sep(),

             ::FractalShark::Radio(L"Patriotic",
                                   ::FractalShark::FractalCommand::PaletteType2,
                                   ::FractalShark::RadioGroup::PaletteType),
             ::FractalShark::Radio(L"Summer",
                                   ::FractalShark::FractalCommand::PaletteType3,
                                   ::FractalShark::RadioGroup::PaletteType),
             ::FractalShark::Radio(L"Random",
                                   ::FractalShark::FractalCommand::PaletteType4,
                                   ::FractalShark::RadioGroup::PaletteType),
             ::FractalShark::Radio(L"Custom",
                                   ::FractalShark::FractalCommand::PaletteType5,
                                   ::FractalShark::RadioGroup::PaletteType,
                                   ::FractalShark::Rule::EnableIfCustomPaletteLoaded),

             ::FractalShark::Sep(),

             ::FractalShark::Item(L"&Create Random Palette",
                                  ::FractalShark::FractalCommand::CreateNewPalette),
             ::FractalShark::Item(L"&Load Custom Palette...",
                                  ::FractalShark::FractalCommand::LoadCustomPalette),

             ::FractalShark::Sep(),

             ::FractalShark::Radio(L"5-bit",
                                   ::FractalShark::FractalCommand::Palette5,
                                   ::FractalShark::RadioGroup::PaletteBitDepth),
             ::FractalShark::Radio(L"6-bit",
                                   ::FractalShark::FractalCommand::Palette6,
                                   ::FractalShark::RadioGroup::PaletteBitDepth),
             ::FractalShark::Radio(L"8-bit",
                                   ::FractalShark::FractalCommand::Palette8,
                                   ::FractalShark::RadioGroup::PaletteBitDepth),
             ::FractalShark::Radio(L"12-bit",
                                   ::FractalShark::FractalCommand::Palette12,
                                   ::FractalShark::RadioGroup::PaletteBitDepth),
             ::FractalShark::Radio(L"16-bit",
                                   ::FractalShark::FractalCommand::Palette16,
                                   ::FractalShark::RadioGroup::PaletteBitDepth),
             ::FractalShark::Radio(L"20-bit",
                                   ::FractalShark::FractalCommand::Palette20,
                                   ::FractalShark::RadioGroup::PaletteBitDepth),

             ::FractalShark::Sep(),

             ::FractalShark::Item(L"Pa&lette Rotation", ::FractalShark::FractalCommand::PaletteRotate)),

    ::FractalShark::Sep(),

    FS_POPUP0(L"Memory Management",
              ::FractalShark::Radio(L"Enable Auto-Save Orbit (delete when done, default)",
                                    ::FractalShark::FractalCommand::PerturbAutosaveOnDelete,
                                    ::FractalShark::RadioGroup::MemoryAutosave),
              ::FractalShark::Radio(L"Enable Auto-Save Orbit (keep files)",
                                    ::FractalShark::FractalCommand::PerturbAutosaveOn,
                                    ::FractalShark::RadioGroup::MemoryAutosave),
              ::FractalShark::Radio(L"Disable Auto-Save Orbit",
                                    ::FractalShark::FractalCommand::PerturbAutosaveOff,
                                    ::FractalShark::RadioGroup::MemoryAutosave)),

    ::FractalShark::Item(L"Show Rendering Details", ::FractalShark::FractalCommand::CurPos),

    FS_POPUP0(
        L"Save",
        ::FractalShark::Item(L"Save Location...", ::FractalShark::FractalCommand::SaveLocation),
        ::FractalShark::Item(L"Save High Res Bitmap", ::FractalShark::FractalCommand::SaveHiResBmp),
        ::FractalShark::Item(L"Save Iterations as Text", ::FractalShark::FractalCommand::SaveItersText),
        ::FractalShark::Item(L"Save Bitmap Ima&ge", ::FractalShark::FractalCommand::SaveBmp),
        ::FractalShark::Sep(),
        ::FractalShark::Item(L"Save Reference Orbit as Text",
                             ::FractalShark::FractalCommand::SaveRefOrbitText),
        ::FractalShark::Item(L"Save Compressed Orbit as Text (simple)",
                             ::FractalShark::FractalCommand::SaveRefOrbitTextSimple),
        ::FractalShark::Item(L"Save Compressed Orbit as Text (max)",
                             ::FractalShark::FractalCommand::SaveRefOrbitTextMax),
        ::FractalShark::Item(L"Save Compressed Orbit (Imagina/max)",
                             ::FractalShark::FractalCommand::SaveRefOrbitImagMax),
        ::FractalShark::Sep(),
        ::FractalShark::Item(L"Benchmark (5x, full recalc)",
                             ::FractalShark::FractalCommand::BenchmarkFull),
        ::FractalShark::Item(L"Benchmark (5x, intermediate only)",
                             ::FractalShark::FractalCommand::BenchmarkInt),
        ::FractalShark::Sep(),
        ::FractalShark::Item(L"Diff Imagina Orbits (choose two)",
                             ::FractalShark::FractalCommand::DiffRefOrbitImagMax)),

    FS_POPUP0(L"Load",
              ::FractalShark::Item(L"Load Location...", ::FractalShark::FractalCommand::LoadLocation),
              ::FractalShark::Item(L"Enter Location", ::FractalShark::FractalCommand::LoadEnterLocation),
              ::FractalShark::Sep(),
              ::FractalShark::Item(L"Load Imagina Orbit (Match)...",
                                   ::FractalShark::FractalCommand::LoadRefOrbitImagMax),
              ::FractalShark::Item(L"Load Imagina Orbit (Use Saved)...",
                                   ::FractalShark::FractalCommand::LoadRefOrbitImagMaxSaved)),

    ::FractalShark::Sep(),
    ::FractalShark::Item(L"E&xit", ::FractalShark::FractalCommand::Exit),
};

#undef FS_POPUP0
#undef FS_POPUP
