// Auto-generated explicit instantiation TU.
// Batch: HpSharkFloat_Conversions
// Tag: P SharedOnly
// This file is generated by HpSharkInstantiate.

#include "../HpSharkFloat_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template class HpSharkFloat<SharkFloatParams>;                                                      \
    template std::string Uint32ToMpf<SharkFloatParams>(                                                 \
        const uint32_t *array, int32_t pow64Exponent, mpf_t &mpfValue);                                 \
    template std::string MpfToString<SharkFloatParams>(const mpf_t mpfValue, size_t precInBits);        \
    /* end */

ExplicitlyInstantiate(SharkParamsSharedOnly256);
ExplicitlyInstantiate(SharkParamsSharedOnly512);
ExplicitlyInstantiate(SharkParamsSharedOnly1024);

#undef ExplicitlyInstantiate
