// Auto-generated explicit instantiation TU.
// Batch: HpSharkFloat_Conversions
// Tag: NR
// This file is generated by HpSharkInstantiate.

#include "../HpSharkFloat_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template class HpSharkFloat<SharkFloatParams>;                                                      \
    template std::string Uint32ToMpf<SharkFloatParams>(                                                 \
        const uint32_t *array, int32_t pow64Exponent, mpf_t &mpfValue);                                 \
    template std::string MpfToString<SharkFloatParams>(const mpf_t mpfValue, size_t precInBits);        \
    /* end */

ExplicitlyInstantiate(SharkParamsNR1);
ExplicitlyInstantiate(SharkParamsNR2);
ExplicitlyInstantiate(SharkParamsNR3);
ExplicitlyInstantiate(SharkParamsNR4);
ExplicitlyInstantiate(SharkParamsNR5);
ExplicitlyInstantiate(SharkParamsNR6);
ExplicitlyInstantiate(SharkParamsNR7);
ExplicitlyInstantiate(SharkParamsNR8);
ExplicitlyInstantiate(SharkParamsNR9);
ExplicitlyInstantiate(SharkParamsNR10);
ExplicitlyInstantiate(SharkParamsNR11);
ExplicitlyInstantiate(SharkParamsNR12);

#undef ExplicitlyInstantiate
