// Auto-generated explicit instantiation TU.
// Batch: HpSharkFloat_Conversions
// Tag: NP
// This file is generated by HpSharkInstantiate.

#include "../HpSharkFloat_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template class HpSharkFloat<SharkFloatParams>;                                                      \
    template std::string Uint32ToMpf<SharkFloatParams>(                                                 \
        const uint32_t *array, int32_t pow64Exponent, mpf_t &mpfValue);                                 \
    template std::string MpfToString<SharkFloatParams>(const mpf_t mpfValue, size_t precInBits);        \
    /* end */

ExplicitlyInstantiate(SharkParamsNP1);
ExplicitlyInstantiate(SharkParamsNP2);
ExplicitlyInstantiate(SharkParamsNP3);
ExplicitlyInstantiate(SharkParamsNP4);
ExplicitlyInstantiate(SharkParamsNP5);
ExplicitlyInstantiate(SharkParamsNP6);
ExplicitlyInstantiate(SharkParamsNP7);
ExplicitlyInstantiate(SharkParamsNP8);
ExplicitlyInstantiate(SharkParamsNP9);
ExplicitlyInstantiate(SharkParamsNP10);
ExplicitlyInstantiate(SharkParamsNP11);
ExplicitlyInstantiate(SharkParamsNP12);

#undef ExplicitlyInstantiate
