// Auto-generated explicit instantiation TU.
// Batch: HpSharkReference
// Tag: NR (SharkParamsNR1..12, float SubType)
// This file is generated by gen_inst_files.cpp.

#include "../KernelInvokeReferencePerf_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>>                                 \
    InitHpSharkReferenceKernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams,             \
                                                 const typename SharkFloatParams::Float hdrRadiusY,     \
                                                 const mpf_t,                                           \
                                                 const mpf_t,                                           \
                                                 uint32_t);                                             \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>>                                 \
    InitHpSharkReferenceKernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams,             \
                                                 const typename SharkFloatParams::Float hdrRadiusY,     \
                                                 const HpSharkFloat<SharkFloatParams> &xNum,            \
                                                 const HpSharkFloat<SharkFloatParams> &yNum,            \
                                                 uint32_t);                                             \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>>                                 \
    InitHpSharkReferenceKernel<SharkFloatParams>(                                                       \
        const HpShark::LaunchParams &launchParams,                                                      \
        const typename SharkFloatParams::Float hdrRadiusY,                                              \
        const HpSharkFloat<SharkFloatParams> &xNum,                                                     \
        const HpSharkFloat<SharkFloatParams> &yNum,                                                     \
        ReferencePreparedTables<SharkFloatParams> &preparedTables);                                     \
    template void InvokeHpSharkReferenceKernel<SharkFloatParams>(                                       \
        const HpShark::LaunchParams &launchParams,                                                      \
        HpSharkReferenceResults<SharkFloatParams> &combo,                                               \
        uint64_t numIters);                                                                             \
    template void ShutdownHpSharkReferenceKernel<SharkFloatParams>(                                     \
        const HpShark::LaunchParams &launchParams,                                                      \
        HpSharkReferenceResults<SharkFloatParams> &combo,                                               \
        DebugGpuCombo *debugCombo);                                                                     \
    template uint64_t EvaluateCriticalOrbitAndDerivs_GPU<SharkFloatParams>(                             \
        const mpf_t,                                                                                    \
        const mpf_t,                                                                                    \
        uint64_t,                                                                                       \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        HDRFloat<double> &,                                                                             \
        HDRFloat<double> &,                                                                             \
        const HpShark::LaunchParams &,                                                                  \
        ReferencePreparedTables<SharkFloatParams> *,                                                    \
        uint64_t,                                                                                       \
        bool (*)(),                                                                                     \
        void (*)(uint64_t, void *),                                                                     \
        void *,                                                                                         \
        uint64_t);                                                                                      \
    template uint64_t EvaluateCriticalOrbitAndDerivs_GPU<SharkFloatParams>(                             \
        const mpf_t,                                                                                    \
        const mpf_t,                                                                                    \
        uint64_t,                                                                                       \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        HDRFloat<double> &,                                                                             \
        HDRFloat<double> &,                                                                             \
        const HpShark::LaunchParams &,                                                                  \
        uint32_t,                                                                                       \
        uint64_t,                                                                                       \
        bool (*)(),                                                                                     \
        void (*)(uint64_t, void *),                                                                     \
        void *,                                                                                         \
        uint64_t);                                                                                      \
    /* end */

namespace HpShark {
ExplicitlyInstantiate(SharkParamsNR1);
ExplicitlyInstantiate(SharkParamsNR2);
ExplicitlyInstantiate(SharkParamsNR3);
ExplicitlyInstantiate(SharkParamsNR4);
ExplicitlyInstantiate(SharkParamsNR5);
ExplicitlyInstantiate(SharkParamsNR6);
ExplicitlyInstantiate(SharkParamsNR7);
ExplicitlyInstantiate(SharkParamsNR8);
ExplicitlyInstantiate(SharkParamsNR9);
ExplicitlyInstantiate(SharkParamsNR10);
ExplicitlyInstantiate(SharkParamsNR11);
ExplicitlyInstantiate(SharkParamsNR12);
ExplicitlyInstantiate(SharkParamsNRSharedOnly256);
ExplicitlyInstantiate(SharkParamsNRSharedOnly512);
ExplicitlyInstantiate(SharkParamsNRSharedOnly1024);
} // namespace HpShark

#undef ExplicitlyInstantiate
