// Auto-generated explicit instantiation TU.
// Batch: HpSharkReference
// Tag: Dbf (SharkParamsDbf1..12, CudaDblflt SubType)
// This file is generated by gen_inst_files.cpp.

#include "..\KernelInvokeReferencePerf_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>> \
    InitHpSharkReferenceKernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    const typename SharkFloatParams::Float hdrRadiusY, \
    const mpf_t, \
    const mpf_t); \
    template void InvokeHpSharkReferenceKernel<SharkFloatParams>( \
    const HpShark::LaunchParams &launchParams, \
    HpSharkReferenceResults<SharkFloatParams> &combo, \
    uint64_t numIters); \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>> \
    InitHpSharkReferenceKernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    const typename SharkFloatParams::Float hdrRadiusY, \
    const HpSharkFloat<SharkFloatParams> &xNum, \
    const HpSharkFloat<SharkFloatParams> &yNum); \
    template void ShutdownHpSharkReferenceKernel<SharkFloatParams>( \
    const HpShark::LaunchParams &launchParams, \
    HpSharkReferenceResults<SharkFloatParams> &combo, \
    DebugGpuCombo *debugCombo); \
    template void EvaluateCriticalOrbitAndDerivs_GPU<SharkFloatParams>( \
    const mpf_t, const mpf_t, uint64_t, \
    mpf_t, mpf_t, mpf_t, mpf_t, \
    HDRFloat<double> &, HDRFloat<double> &, \
    const HpShark::LaunchParams &); \
    /* end */

namespace HpShark {
ExplicitlyInstantiate(SharkParamsDbf1);
ExplicitlyInstantiate(SharkParamsDbf2);
ExplicitlyInstantiate(SharkParamsDbf3);
ExplicitlyInstantiate(SharkParamsDbf4);
ExplicitlyInstantiate(SharkParamsDbf5);
ExplicitlyInstantiate(SharkParamsDbf6);
ExplicitlyInstantiate(SharkParamsDbf7);
ExplicitlyInstantiate(SharkParamsDbf8);
ExplicitlyInstantiate(SharkParamsDbf9);
ExplicitlyInstantiate(SharkParamsDbf10);
ExplicitlyInstantiate(SharkParamsDbf11);
ExplicitlyInstantiate(SharkParamsDbf12);
} // namespace HpShark

#undef ExplicitlyInstantiate
