// Auto-generated explicit instantiation TU.
// Batch: HpSharkReference2
// Tag: NR (SharkParamsNR1..12, float SubType)
// This file is generated by gen_inst_files.cpp.

#include "../KernelInvokeReference2Perf_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>>                                 \
    InitHpSharkReference2Kernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams,            \
                                                  const typename SharkFloatParams::Float hdrRadiusY,    \
                                                  const mpf_t,                                          \
                                                  const mpf_t);                                         \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>>                                 \
    InitHpSharkReference2Kernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams,            \
                                                  const typename SharkFloatParams::Float hdrRadiusY,    \
                                                  const HpSharkFloat<SharkFloatParams> &xNum,           \
                                                  const HpSharkFloat<SharkFloatParams> &yNum);          \
    template void InvokeHpSharkReference2Kernel<SharkFloatParams>(                                      \
        const HpShark::LaunchParams &launchParams,                                                      \
        HpSharkReferenceResults<SharkFloatParams> &combo,                                               \
        uint64_t numIters);                                                                             \
    template uint64_t EvaluateCriticalOrbitAndDerivs2_GPU<SharkFloatParams>(                            \
        const mpf_t,                                                                                    \
        const mpf_t,                                                                                    \
        uint64_t,                                                                                       \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        HDRFloat<double> &,                                                                             \
        HDRFloat<double> &,                                                                             \
        const HpShark::LaunchParams &,                                                                  \
        uint64_t,                                                                                       \
        bool (*)(),                                                                                     \
        void (*)(uint64_t, void *),                                                                     \
        void *,                                                                                         \
        uint64_t);                                                                                      \
    /* end */

namespace HpShark {
ExplicitlyInstantiate(SharkParamsNR1);
ExplicitlyInstantiate(SharkParamsNR2);
ExplicitlyInstantiate(SharkParamsNR3);
ExplicitlyInstantiate(SharkParamsNR4);
ExplicitlyInstantiate(SharkParamsNR5);
ExplicitlyInstantiate(SharkParamsNR6);
ExplicitlyInstantiate(SharkParamsNR7);
ExplicitlyInstantiate(SharkParamsNR8);
ExplicitlyInstantiate(SharkParamsNR9);
ExplicitlyInstantiate(SharkParamsNR10);
ExplicitlyInstantiate(SharkParamsNR11);
ExplicitlyInstantiate(SharkParamsNR12);
} // namespace HpShark

#undef ExplicitlyInstantiate
