// Auto-generated explicit instantiation TU.
// Batch: ReferenceGpuLoop
// Tag: NR (SharkParamsNR1..12, float SubType)
// This file is generated by gen_inst_files.cpp.

#include "../KernelHpSharkReferenceOrbit_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template void ComputeHpSharkReferenceGpuLoop<SharkFloatParams>(                                     \
        const HpShark::LaunchParams &launchParams, cudaStream_t &stream, void *kernelArgs[]);           \
    template void ComputeHpSharkReferenceSetup<SharkFloatParams>(                                       \
        const HpShark::LaunchParams &launchParams, cudaStream_t &stream, void *kernelArgs[]);           \
    /* end */

ExplicitlyInstantiate(SharkParamsNR1);
ExplicitlyInstantiate(SharkParamsNR2);
ExplicitlyInstantiate(SharkParamsNR3);
ExplicitlyInstantiate(SharkParamsNR4);
ExplicitlyInstantiate(SharkParamsNR5);
ExplicitlyInstantiate(SharkParamsNR6);
ExplicitlyInstantiate(SharkParamsNR7);
ExplicitlyInstantiate(SharkParamsNR8);
ExplicitlyInstantiate(SharkParamsNR9);
ExplicitlyInstantiate(SharkParamsNR10);
ExplicitlyInstantiate(SharkParamsNR11);
ExplicitlyInstantiate(SharkParamsNR12);
ExplicitlyInstantiate(SharkParamsNRSharedOnly256);
ExplicitlyInstantiate(SharkParamsNRSharedOnly512);
ExplicitlyInstantiate(SharkParamsNRSharedOnly1024);

#undef ExplicitlyInstantiate
