// Auto-generated explicit instantiation TU.
// Batch: HpSharkReference
// Tag: P (SharkParams1..12)
// This file is generated by gen_inst_files.cpp.

#include "..\KernelInvokeReferencePerf_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>> \
    InitHpSharkReferenceKernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    const typename SharkFloatParams::Float hdrRadiusY, \
    const mpf_t, \
    const mpf_t); \
    template void InvokeHpSharkReferenceKernel<SharkFloatParams>( \
    const HpShark::LaunchParams &launchParams, \
    HpSharkReferenceResults<SharkFloatParams> &combo, \
    uint64_t numIters); \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>> \
    InitHpSharkReferenceKernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    const typename SharkFloatParams::Float hdrRadiusY, \
    const HpSharkFloat<SharkFloatParams> &xNum, \
    const HpSharkFloat<SharkFloatParams> &yNum); \
    template void ShutdownHpSharkReferenceKernel<SharkFloatParams>( \
    const HpShark::LaunchParams &launchParams, \
    HpSharkReferenceResults<SharkFloatParams> &combo, \
    DebugGpuCombo *debugCombo); \
    /* end */

namespace HpShark {
ExplicitlyInstantiate(SharkParams1);
ExplicitlyInstantiate(SharkParams2);
ExplicitlyInstantiate(SharkParams3);
ExplicitlyInstantiate(SharkParams4);
ExplicitlyInstantiate(SharkParams5);
ExplicitlyInstantiate(SharkParams6);
ExplicitlyInstantiate(SharkParams7);
ExplicitlyInstantiate(SharkParams8);
ExplicitlyInstantiate(SharkParams9);
ExplicitlyInstantiate(SharkParams10);
ExplicitlyInstantiate(SharkParams11);
ExplicitlyInstantiate(SharkParams12);
} // namespace HpShark

#undef ExplicitlyInstantiate
