// Auto-generated explicit instantiation TU.
// Batch: SharkNTT_Primitives
// Tag: NP
// This file is generated by HpSharkInstantiate.

#include "../ReferenceNTT_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template uint64_t SharkNTT::MontgomeryMul<SharkFloatParams>(uint64_t a, uint64_t b);                \
    template uint64_t SharkNTT::MontgomeryMul<SharkFloatParams>(                                        \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t a, uint64_t b);                         \
    template uint64_t SharkNTT::ToMontgomery<SharkFloatParams>(uint64_t value);                         \
    template uint64_t SharkNTT::ToMontgomery<SharkFloatParams>(                                         \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t value);                                 \
    template uint64_t SharkNTT::FromMontgomery<SharkFloatParams>(uint64_t value);                       \
    template uint64_t SharkNTT::FromMontgomery<SharkFloatParams>(                                       \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t value);                                 \
    template uint64_t SharkNTT::MontgomeryPow<SharkFloatParams>(uint64_t value, uint64_t exponent);     \
    template uint64_t SharkNTT::MontgomeryPow<SharkFloatParams>(                                        \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t value, uint64_t exponent);              \
    /* end */

ExplicitlyInstantiate(SharkParamsNP1);
ExplicitlyInstantiate(SharkParamsNP2);
ExplicitlyInstantiate(SharkParamsNP3);
ExplicitlyInstantiate(SharkParamsNP4);
ExplicitlyInstantiate(SharkParamsNP5);
ExplicitlyInstantiate(SharkParamsNP6);
ExplicitlyInstantiate(SharkParamsNP7);
ExplicitlyInstantiate(SharkParamsNP8);
ExplicitlyInstantiate(SharkParamsNP9);
ExplicitlyInstantiate(SharkParamsNP10);
ExplicitlyInstantiate(SharkParamsNP11);
ExplicitlyInstantiate(SharkParamsNP12);

#undef ExplicitlyInstantiate
