// Auto-generated explicit instantiation TU.
// Batch: MultiplyNTT
// Tag: P (SharkParams1..12, SharkParamsNR*)
// This file is generated by gen_inst_files.cpp.

#include "..\KernelTestMultiplyNTT_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template void ComputeMultiplyNTTGpu<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    void *kernelArgs[]); \
    template void ComputeMultiplyNTTGpuTestLoop<SharkFloatParams>( \
    const HpShark::LaunchParams &launchParams, cudaStream_t &stream, void *kernelArgs[]); \
    /* end */

ExplicitlyInstantiate(SharkParams1);
ExplicitlyInstantiate(SharkParams2);
ExplicitlyInstantiate(SharkParams3);
ExplicitlyInstantiate(SharkParams4);
ExplicitlyInstantiate(SharkParams5);
ExplicitlyInstantiate(SharkParams6);
ExplicitlyInstantiate(SharkParams7);
ExplicitlyInstantiate(SharkParams8);
ExplicitlyInstantiate(SharkParams9);
ExplicitlyInstantiate(SharkParams10);
ExplicitlyInstantiate(SharkParams11);
ExplicitlyInstantiate(SharkParams12);
ExplicitlyInstantiate(SharkParamsNR1);
ExplicitlyInstantiate(SharkParamsNR2);
ExplicitlyInstantiate(SharkParamsNR3);
ExplicitlyInstantiate(SharkParamsNR4);
ExplicitlyInstantiate(SharkParamsNR5);
ExplicitlyInstantiate(SharkParamsNR6);
ExplicitlyInstantiate(SharkParamsNR7);
ExplicitlyInstantiate(SharkParamsNR8);
ExplicitlyInstantiate(SharkParamsNR9);
ExplicitlyInstantiate(SharkParamsNR10);
ExplicitlyInstantiate(SharkParamsNR11);
ExplicitlyInstantiate(SharkParamsNR12);
ExplicitlyInstantiate(SharkParamsDbl1);
ExplicitlyInstantiate(SharkParamsDbl2);
ExplicitlyInstantiate(SharkParamsDbl3);
ExplicitlyInstantiate(SharkParamsDbl4);
ExplicitlyInstantiate(SharkParamsDbl5);
ExplicitlyInstantiate(SharkParamsDbl6);
ExplicitlyInstantiate(SharkParamsDbl7);
ExplicitlyInstantiate(SharkParamsDbl8);
ExplicitlyInstantiate(SharkParamsDbl9);
ExplicitlyInstantiate(SharkParamsDbl10);
ExplicitlyInstantiate(SharkParamsDbl11);
ExplicitlyInstantiate(SharkParamsDbl12);
ExplicitlyInstantiate(SharkParamsDbf1);
ExplicitlyInstantiate(SharkParamsDbf2);
ExplicitlyInstantiate(SharkParamsDbf3);
ExplicitlyInstantiate(SharkParamsDbf4);
ExplicitlyInstantiate(SharkParamsDbf5);
ExplicitlyInstantiate(SharkParamsDbf6);
ExplicitlyInstantiate(SharkParamsDbf7);
ExplicitlyInstantiate(SharkParamsDbf8);
ExplicitlyInstantiate(SharkParamsDbf9);
ExplicitlyInstantiate(SharkParamsDbf10);
ExplicitlyInstantiate(SharkParamsDbf11);
ExplicitlyInstantiate(SharkParamsDbf12);

#undef ExplicitlyInstantiate
