// Auto-generated explicit instantiation TU.
// Batch: HpSharkReference
// Tag: NP (SharkParamsNP1..12)
// This file is generated by gen_inst_files.cpp.

#include "..\KernelInvokeReferencePerf_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>> \
    InitHpSharkReferenceKernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    const typename SharkFloatParams::Float hdrRadiusY, \
    const mpf_t, \
    const mpf_t); \
    template void InvokeHpSharkReferenceKernel<SharkFloatParams>( \
    const HpShark::LaunchParams &launchParams, \
    HpSharkReferenceResults<SharkFloatParams> &combo, \
    uint64_t numIters); \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>> \
    InitHpSharkReferenceKernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    const typename SharkFloatParams::Float hdrRadiusY, \
    const HpSharkFloat<SharkFloatParams> &xNum, \
    const HpSharkFloat<SharkFloatParams> &yNum); \
    template void ShutdownHpSharkReferenceKernel<SharkFloatParams>( \
    const HpShark::LaunchParams &launchParams, \
    HpSharkReferenceResults<SharkFloatParams> &combo, \
    DebugGpuCombo *debugCombo); \
    /* end */

namespace HpShark {
ExplicitlyInstantiate(SharkParamsNP1);
ExplicitlyInstantiate(SharkParamsNP2);
ExplicitlyInstantiate(SharkParamsNP3);
ExplicitlyInstantiate(SharkParamsNP4);
ExplicitlyInstantiate(SharkParamsNP5);
ExplicitlyInstantiate(SharkParamsNP6);
ExplicitlyInstantiate(SharkParamsNP7);
ExplicitlyInstantiate(SharkParamsNP8);
ExplicitlyInstantiate(SharkParamsNP9);
ExplicitlyInstantiate(SharkParamsNP10);
ExplicitlyInstantiate(SharkParamsNP11);
ExplicitlyInstantiate(SharkParamsNP12);
} // namespace HpShark

#undef ExplicitlyInstantiate
