// Auto-generated explicit instantiation TU.
// Batch: AddKernels
// Tag: P (SharkParams1..12)
// This file is generated by gen_inst_files.cpp.

#include "..\KernelTestAdd_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template void ComputeAddGpu<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    void *kernelArgs[]); \
    template void ComputeAddGpuTestLoop<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    void *kernelArgs[]); \
    /* end */

ExplicitlyInstantiate(SharkParams1);
ExplicitlyInstantiate(SharkParams2);
ExplicitlyInstantiate(SharkParams3);
ExplicitlyInstantiate(SharkParams4);
ExplicitlyInstantiate(SharkParams5);
ExplicitlyInstantiate(SharkParams6);
ExplicitlyInstantiate(SharkParams7);
ExplicitlyInstantiate(SharkParams8);
ExplicitlyInstantiate(SharkParams9);
ExplicitlyInstantiate(SharkParams10);
ExplicitlyInstantiate(SharkParams11);
ExplicitlyInstantiate(SharkParams12);

#undef ExplicitlyInstantiate
