// Auto-generated explicit instantiation TU.
// Batch: HpSharkReference
// Tag: Dbf SharedOnly
// This file is generated by HpSharkInstantiate.

#include "../KernelInvokeReferencePerf_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>>                                 \
    InitHpSharkReferenceKernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams,             \
                                                 const typename SharkFloatParams::Float hdrRadiusY,     \
                                                 const mpf_t,                                           \
                                                 const mpf_t,                                           \
                                                 uint32_t);                                             \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>>                                 \
    InitHpSharkReferenceKernel<SharkFloatParams>(const HpShark::LaunchParams &launchParams,             \
                                                 const typename SharkFloatParams::Float hdrRadiusY,     \
                                                 const HpSharkFloat<SharkFloatParams> &xNum,            \
                                                 const HpSharkFloat<SharkFloatParams> &yNum,            \
                                                 uint32_t);                                             \
    template std::unique_ptr<HpSharkReferenceResults<SharkFloatParams>>                                 \
    InitHpSharkReferenceKernel<SharkFloatParams>(                                                       \
        const HpShark::LaunchParams &launchParams,                                                      \
        const typename SharkFloatParams::Float hdrRadiusY,                                              \
        const HpSharkFloat<SharkFloatParams> &xNum,                                                     \
        const HpSharkFloat<SharkFloatParams> &yNum,                                                     \
        ReferencePreparedTables<SharkFloatParams> &preparedTables);                                     \
    template void InvokeHpSharkReferenceKernel<SharkFloatParams>(                                       \
        const HpShark::LaunchParams &launchParams,                                                      \
        HpSharkReferenceResults<SharkFloatParams> &results,                                             \
        uint64_t numIters);                                                                             \
    template void ShutdownHpSharkReferenceKernel<SharkFloatParams>(                                     \
        const HpShark::LaunchParams &launchParams,                                                      \
        HpSharkReferenceResults<SharkFloatParams> &results,                                             \
        DebugGpuCombo *debugResults);                                                                   \
    template uint64_t EvaluateCriticalOrbitAndDerivs_GPU<SharkFloatParams>(                             \
        const mpf_t,                                                                                    \
        const mpf_t,                                                                                    \
        uint64_t,                                                                                       \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        HDRFloat<double> &,                                                                             \
        HDRFloat<double> &,                                                                             \
        const HpShark::LaunchParams &,                                                                  \
        ReferencePreparedTables<SharkFloatParams> *,                                                    \
        uint64_t,                                                                                       \
        bool (*)(),                                                                                     \
        void (*)(uint64_t, void *),                                                                     \
        void *,                                                                                         \
        uint64_t);                                                                                      \
    template uint64_t EvaluateCriticalOrbitAndDerivs_GPU<SharkFloatParams>(                             \
        const mpf_t,                                                                                    \
        const mpf_t,                                                                                    \
        uint64_t,                                                                                       \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        mpf_t,                                                                                          \
        HDRFloat<double> &,                                                                             \
        HDRFloat<double> &,                                                                             \
        const HpShark::LaunchParams &,                                                                  \
        uint32_t,                                                                                       \
        uint64_t,                                                                                       \
        bool (*)(),                                                                                     \
        void (*)(uint64_t, void *),                                                                     \
        void *,                                                                                         \
        uint64_t);                                                                                      \
    /* end */

namespace HpShark {
ExplicitlyInstantiate(SharkParamsDbfSharedOnly256);
ExplicitlyInstantiate(SharkParamsDbfSharedOnly512);
ExplicitlyInstantiate(SharkParamsDbfSharedOnly1024);
} // namespace HpShark

#undef ExplicitlyInstantiate
