// Auto-generated explicit instantiation TU.
// Batch: AddKernels
// Tag: NR (SharkParamsNR1..12, float SubType)
// This file is generated by gen_inst_files.cpp.

#include "../KernelTestAdd_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template void ComputeAddGpu<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    void *kernelArgs[]); \
    template void ComputeAddGpuTestLoop<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    void *kernelArgs[]); \
    /* end */

ExplicitlyInstantiate(SharkParamsNR1);
ExplicitlyInstantiate(SharkParamsNR2);
ExplicitlyInstantiate(SharkParamsNR3);
ExplicitlyInstantiate(SharkParamsNR4);
ExplicitlyInstantiate(SharkParamsNR5);
ExplicitlyInstantiate(SharkParamsNR6);
ExplicitlyInstantiate(SharkParamsNR7);
ExplicitlyInstantiate(SharkParamsNR8);
ExplicitlyInstantiate(SharkParamsNR9);
ExplicitlyInstantiate(SharkParamsNR10);
ExplicitlyInstantiate(SharkParamsNR11);
ExplicitlyInstantiate(SharkParamsNR12);

#undef ExplicitlyInstantiate
