// Auto-generated explicit instantiation TU.
// Batch: SharkNTT_Primitives
// Tag: NP (SharkParamsNP1..12)
// This file is generated by gen_inst_files.cpp.

#include "..\MultiplyNTTCudaSetup_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template void SharkNTT::BuildRoots<SharkFloatParams>(uint32_t, uint32_t, SharkNTT::RootTables &); \
    template uint64_t SharkNTT::MontgomeryMul<SharkFloatParams>(uint64_t a, uint64_t b); \
    template uint64_t SharkNTT::MontgomeryMul<SharkFloatParams>( \
    DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t a, uint64_t b); \
    template uint64_t SharkNTT::ToMontgomery<SharkFloatParams>(uint64_t x); \
    template uint64_t SharkNTT::ToMontgomery<SharkFloatParams>( \
    DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t x); \
    template uint64_t SharkNTT::FromMontgomery<SharkFloatParams>(uint64_t x); \
    template uint64_t SharkNTT::FromMontgomery<SharkFloatParams>( \
    DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t x); \
    template uint64_t SharkNTT::MontgomeryPow<SharkFloatParams>(uint64_t a_mont, uint64_t e); \
    template uint64_t SharkNTT::MontgomeryPow<SharkFloatParams>( \
    DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t a_mont, uint64_t e); \
    template void SharkNTT::CopyRootsToCuda<SharkFloatParams>(SharkNTT::RootTables & outT, \
    const SharkNTT::RootTables &inT); \
    template void SharkNTT::DestroyRoots<SharkFloatParams>(bool cuda, SharkNTT::RootTables &T); \
    /* end */

ExplicitlyInstantiate(SharkParamsNP1);
ExplicitlyInstantiate(SharkParamsNP2);
ExplicitlyInstantiate(SharkParamsNP3);
ExplicitlyInstantiate(SharkParamsNP4);
ExplicitlyInstantiate(SharkParamsNP5);
ExplicitlyInstantiate(SharkParamsNP6);
ExplicitlyInstantiate(SharkParamsNP7);
ExplicitlyInstantiate(SharkParamsNP8);
ExplicitlyInstantiate(SharkParamsNP9);
ExplicitlyInstantiate(SharkParamsNP10);
ExplicitlyInstantiate(SharkParamsNP11);
ExplicitlyInstantiate(SharkParamsNP12);

#undef ExplicitlyInstantiate
