// Auto-generated explicit instantiation TU.
// Batch: AddKernels
// Tag: P + NP (SharkParams1..12 + SharkParamsNP1..12, float SubType)
// This file is generated by gen_inst_files.cpp.

#include "..\KernelTestAdd_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template void ComputeAddGpu<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    void *kernelArgs[]); \
    template void ComputeAddGpuTestLoop<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    void *kernelArgs[]); \
    /* end */

ExplicitlyInstantiate(SharkParams1);
ExplicitlyInstantiate(SharkParams2);
ExplicitlyInstantiate(SharkParams3);
ExplicitlyInstantiate(SharkParams4);
ExplicitlyInstantiate(SharkParams5);
ExplicitlyInstantiate(SharkParams6);
ExplicitlyInstantiate(SharkParams7);
ExplicitlyInstantiate(SharkParams8);
ExplicitlyInstantiate(SharkParams9);
ExplicitlyInstantiate(SharkParams10);
ExplicitlyInstantiate(SharkParams11);
ExplicitlyInstantiate(SharkParams12);
ExplicitlyInstantiate(SharkParamsNP1);
ExplicitlyInstantiate(SharkParamsNP2);
ExplicitlyInstantiate(SharkParamsNP3);
ExplicitlyInstantiate(SharkParamsNP4);
ExplicitlyInstantiate(SharkParamsNP5);
ExplicitlyInstantiate(SharkParamsNP6);
ExplicitlyInstantiate(SharkParamsNP7);
ExplicitlyInstantiate(SharkParamsNP8);
ExplicitlyInstantiate(SharkParamsNP9);
ExplicitlyInstantiate(SharkParamsNP10);
ExplicitlyInstantiate(SharkParamsNP11);
ExplicitlyInstantiate(SharkParamsNP12);

#undef ExplicitlyInstantiate
