// Auto-generated explicit instantiation TU.
// Batch: ReferenceGpuLoop
// Tag: NP
// This file is generated by HpSharkInstantiate.

#include "../KernelHpSharkReferenceOrbit_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template void ComputeHpSharkReferenceGpuLoop<SharkFloatParams>(                                     \
        const HpShark::LaunchParams &launchParams, cudaStream_t &stream, void *kernelArgs[]);           \
    template void ComputeHpSharkReferenceSetup<SharkFloatParams>(                                       \
        const HpShark::LaunchParams &launchParams, cudaStream_t &stream, void *kernelArgs[]);           \
    /* end */

ExplicitlyInstantiate(SharkParamsNP1);
ExplicitlyInstantiate(SharkParamsNP2);
ExplicitlyInstantiate(SharkParamsNP3);
ExplicitlyInstantiate(SharkParamsNP4);
ExplicitlyInstantiate(SharkParamsNP5);
ExplicitlyInstantiate(SharkParamsNP6);
ExplicitlyInstantiate(SharkParamsNP7);
ExplicitlyInstantiate(SharkParamsNP8);
ExplicitlyInstantiate(SharkParamsNP9);
ExplicitlyInstantiate(SharkParamsNP10);
ExplicitlyInstantiate(SharkParamsNP11);
ExplicitlyInstantiate(SharkParamsNP12);

#undef ExplicitlyInstantiate
