// Auto-generated explicit instantiation TU.
// Batch: ReferenceGpuLoop
// Tag: P SharedOnly
// This file is generated by HpSharkInstantiate.

#include "../KernelHpSharkReferenceOrbit_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template void ComputeHpSharkReferenceGpuLoop<SharkFloatParams>(                                     \
        const HpShark::LaunchParams &launchParams, cudaStream_t &stream, void *kernelArgs[]);           \
    template void ComputeHpSharkReferenceSetup<SharkFloatParams>(                                       \
        const HpShark::LaunchParams &launchParams, cudaStream_t &stream, void *kernelArgs[]);           \
    /* end */

ExplicitlyInstantiate(SharkParamsSharedOnly256);
ExplicitlyInstantiate(SharkParamsSharedOnly512);
ExplicitlyInstantiate(SharkParamsSharedOnly1024);

#undef ExplicitlyInstantiate
