// Auto-generated explicit instantiation TU.
// Batch: HpSharkFloat_Conversions
// Tag: NP (SharkParamsNP1..12)
// This file is generated by gen_inst_files.cpp.

#include "..\HpSharkFloat_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template class HpSharkFloat<SharkFloatParams>; \
    template std::string Uint32ToMpf<SharkFloatParams>( \
    const uint32_t *array, int32_t pow64Exponent, mpf_t &mpf_val); \
    template std::string MpfToString<SharkFloatParams>(const mpf_t mpf_val, size_t precInBits); \
    /* end */

ExplicitlyInstantiate(SharkParamsNP1);
ExplicitlyInstantiate(SharkParamsNP2);
ExplicitlyInstantiate(SharkParamsNP3);
ExplicitlyInstantiate(SharkParamsNP4);
ExplicitlyInstantiate(SharkParamsNP5);
ExplicitlyInstantiate(SharkParamsNP6);
ExplicitlyInstantiate(SharkParamsNP7);
ExplicitlyInstantiate(SharkParamsNP8);
ExplicitlyInstantiate(SharkParamsNP9);
ExplicitlyInstantiate(SharkParamsNP10);
ExplicitlyInstantiate(SharkParamsNP11);
ExplicitlyInstantiate(SharkParamsNP12);

#undef ExplicitlyInstantiate
