// Auto-generated explicit instantiation TU.
// Batch: ReferenceGpuLoop
// Tag: Dbf
// This file is generated by HpSharkInstantiate.

#include "../KernelHpSharkReferenceOrbit_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template void ComputeHpSharkReferenceGpuLoop<SharkFloatParams>(                                     \
        const HpShark::LaunchParams &launchParams, cudaStream_t &stream, void *kernelArgs[]);           \
    template void ComputeHpSharkReferenceSetup<SharkFloatParams>(                                       \
        const HpShark::LaunchParams &launchParams, cudaStream_t &stream, void *kernelArgs[]);           \
    /* end */

ExplicitlyInstantiate(SharkParamsDbf1);
ExplicitlyInstantiate(SharkParamsDbf2);
ExplicitlyInstantiate(SharkParamsDbf3);
ExplicitlyInstantiate(SharkParamsDbf4);
ExplicitlyInstantiate(SharkParamsDbf5);
ExplicitlyInstantiate(SharkParamsDbf6);
ExplicitlyInstantiate(SharkParamsDbf7);
ExplicitlyInstantiate(SharkParamsDbf8);
ExplicitlyInstantiate(SharkParamsDbf9);
ExplicitlyInstantiate(SharkParamsDbf10);
ExplicitlyInstantiate(SharkParamsDbf11);
ExplicitlyInstantiate(SharkParamsDbf12);

#undef ExplicitlyInstantiate
