// Auto-generated explicit instantiation TU.
// Batch: MultiplyNTT
// Tag: Dbf (SharkParamsDbf1..12, CudaDblflt SubType)
// This file is generated by gen_inst_files.cpp.

#include "..\KernelTestMultiplyNTT_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template void ComputeMultiplyNTTGpu<SharkFloatParams>(const HpShark::LaunchParams &launchParams, \
    void *kernelArgs[]); \
    template void ComputeMultiplyNTTGpuTestLoop<SharkFloatParams>( \
    const HpShark::LaunchParams &launchParams, cudaStream_t &stream, void *kernelArgs[]); \
    /* end */

ExplicitlyInstantiate(SharkParamsDbf1);
ExplicitlyInstantiate(SharkParamsDbf2);
ExplicitlyInstantiate(SharkParamsDbf3);
ExplicitlyInstantiate(SharkParamsDbf4);
ExplicitlyInstantiate(SharkParamsDbf5);
ExplicitlyInstantiate(SharkParamsDbf6);
ExplicitlyInstantiate(SharkParamsDbf7);
ExplicitlyInstantiate(SharkParamsDbf8);
ExplicitlyInstantiate(SharkParamsDbf9);
ExplicitlyInstantiate(SharkParamsDbf10);
ExplicitlyInstantiate(SharkParamsDbf11);
ExplicitlyInstantiate(SharkParamsDbf12);

#undef ExplicitlyInstantiate
