// Auto-generated explicit instantiation TU.
// Batch: HpSharkFloat_Conversions
// Tag: P
// This file is generated by HpSharkInstantiate.

#include "../HpSharkFloat_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template class HpSharkFloat<SharkFloatParams>;                                                      \
    template std::string Uint32ToMpf<SharkFloatParams>(                                                 \
        const uint32_t *array, int32_t pow64Exponent, mpf_t &mpfValue);                                 \
    template std::string MpfToString<SharkFloatParams>(const mpf_t mpfValue, size_t precInBits);        \
    /* end */

ExplicitlyInstantiate(SharkParams1);
ExplicitlyInstantiate(SharkParams2);
ExplicitlyInstantiate(SharkParams3);
ExplicitlyInstantiate(SharkParams4);
ExplicitlyInstantiate(SharkParams5);
ExplicitlyInstantiate(SharkParams6);
ExplicitlyInstantiate(SharkParams7);
ExplicitlyInstantiate(SharkParams8);
ExplicitlyInstantiate(SharkParams9);
ExplicitlyInstantiate(SharkParams10);
ExplicitlyInstantiate(SharkParams11);
ExplicitlyInstantiate(SharkParams12);

#undef ExplicitlyInstantiate
