// Auto-generated explicit instantiation TU.
// Batch: SharkNTT_Primitives
// Tag: Dbl
// This file is generated by HpSharkInstantiate.

#include "../ReferenceNTT_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template uint64_t SharkNTT::MontgomeryMul<SharkFloatParams>(uint64_t a, uint64_t b);                \
    template uint64_t SharkNTT::MontgomeryMul<SharkFloatParams>(                                        \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t a, uint64_t b);                         \
    template uint64_t SharkNTT::ToMontgomery<SharkFloatParams>(uint64_t value);                         \
    template uint64_t SharkNTT::ToMontgomery<SharkFloatParams>(                                         \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t value);                                 \
    template uint64_t SharkNTT::FromMontgomery<SharkFloatParams>(uint64_t value);                       \
    template uint64_t SharkNTT::FromMontgomery<SharkFloatParams>(                                       \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t value);                                 \
    template uint64_t SharkNTT::MontgomeryPow<SharkFloatParams>(uint64_t value, uint64_t exponent);     \
    template uint64_t SharkNTT::MontgomeryPow<SharkFloatParams>(                                        \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t value, uint64_t exponent);              \
    /* end */

ExplicitlyInstantiate(SharkParamsDbl1);
ExplicitlyInstantiate(SharkParamsDbl2);
ExplicitlyInstantiate(SharkParamsDbl3);
ExplicitlyInstantiate(SharkParamsDbl4);
ExplicitlyInstantiate(SharkParamsDbl5);
ExplicitlyInstantiate(SharkParamsDbl6);
ExplicitlyInstantiate(SharkParamsDbl7);
ExplicitlyInstantiate(SharkParamsDbl8);
ExplicitlyInstantiate(SharkParamsDbl9);
ExplicitlyInstantiate(SharkParamsDbl10);
ExplicitlyInstantiate(SharkParamsDbl11);
ExplicitlyInstantiate(SharkParamsDbl12);

#undef ExplicitlyInstantiate
