// Auto-generated explicit instantiation TU.
// Batch: HpSharkReference2
// Tag: Dbl + Dbf (SharkParamsDbl1..12 + SharkParamsDbf1..12)
// This file is generated by gen_inst_files.cpp.

#include "../KernelInvokeReference2Perf_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template void InvokeHpSharkReference2Kernel<SharkFloatParams>( \
    const HpShark::LaunchParams &launchParams, \
    HpSharkReferenceResults<SharkFloatParams> &combo, \
    uint64_t numIters); \
    /* end */

namespace HpShark {
ExplicitlyInstantiate(SharkParamsDbl1);
ExplicitlyInstantiate(SharkParamsDbl2);
ExplicitlyInstantiate(SharkParamsDbl3);
ExplicitlyInstantiate(SharkParamsDbl4);
ExplicitlyInstantiate(SharkParamsDbl5);
ExplicitlyInstantiate(SharkParamsDbl6);
ExplicitlyInstantiate(SharkParamsDbl7);
ExplicitlyInstantiate(SharkParamsDbl8);
ExplicitlyInstantiate(SharkParamsDbl9);
ExplicitlyInstantiate(SharkParamsDbl10);
ExplicitlyInstantiate(SharkParamsDbl11);
ExplicitlyInstantiate(SharkParamsDbl12);
ExplicitlyInstantiate(SharkParamsDbf1);
ExplicitlyInstantiate(SharkParamsDbf2);
ExplicitlyInstantiate(SharkParamsDbf3);
ExplicitlyInstantiate(SharkParamsDbf4);
ExplicitlyInstantiate(SharkParamsDbf5);
ExplicitlyInstantiate(SharkParamsDbf6);
ExplicitlyInstantiate(SharkParamsDbf7);
ExplicitlyInstantiate(SharkParamsDbf8);
ExplicitlyInstantiate(SharkParamsDbf9);
ExplicitlyInstantiate(SharkParamsDbf10);
ExplicitlyInstantiate(SharkParamsDbf11);
ExplicitlyInstantiate(SharkParamsDbf12);
} // namespace HpShark

#undef ExplicitlyInstantiate
