// Auto-generated explicit instantiation TU.
// Batch: SharkNTT_Primitives
// Tag: Dbf
// This file is generated by HpSharkInstantiate.

#include "../ReferenceNTT_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams)                                                         \
    template uint64_t SharkNTT::MontgomeryMul<SharkFloatParams>(uint64_t a, uint64_t b);                \
    template uint64_t SharkNTT::MontgomeryMul<SharkFloatParams>(                                        \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t a, uint64_t b);                         \
    template uint64_t SharkNTT::ToMontgomery<SharkFloatParams>(uint64_t value);                         \
    template uint64_t SharkNTT::ToMontgomery<SharkFloatParams>(                                         \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t value);                                 \
    template uint64_t SharkNTT::FromMontgomery<SharkFloatParams>(uint64_t value);                       \
    template uint64_t SharkNTT::FromMontgomery<SharkFloatParams>(                                       \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t value);                                 \
    template uint64_t SharkNTT::MontgomeryPow<SharkFloatParams>(uint64_t value, uint64_t exponent);     \
    template uint64_t SharkNTT::MontgomeryPow<SharkFloatParams>(                                        \
        DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t value, uint64_t exponent);              \
    /* end */

ExplicitlyInstantiate(SharkParamsDbf1);
ExplicitlyInstantiate(SharkParamsDbf2);
ExplicitlyInstantiate(SharkParamsDbf3);
ExplicitlyInstantiate(SharkParamsDbf4);
ExplicitlyInstantiate(SharkParamsDbf5);
ExplicitlyInstantiate(SharkParamsDbf6);
ExplicitlyInstantiate(SharkParamsDbf7);
ExplicitlyInstantiate(SharkParamsDbf8);
ExplicitlyInstantiate(SharkParamsDbf9);
ExplicitlyInstantiate(SharkParamsDbf10);
ExplicitlyInstantiate(SharkParamsDbf11);
ExplicitlyInstantiate(SharkParamsDbf12);

#undef ExplicitlyInstantiate
