// Auto-generated explicit instantiation TU.
// Batch: SharkNTT_Primitives
// Tag: Dbl (SharkParamsDbl1..12, double SubType)
// This file is generated by gen_inst_files.cpp.

#include "..\MultiplyNTTCudaSetup_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template void SharkNTT::BuildRoots<SharkFloatParams>(uint32_t, uint32_t, SharkNTT::RootTables &); \
    template uint64_t SharkNTT::MontgomeryMul<SharkFloatParams>(uint64_t a, uint64_t b); \
    template uint64_t SharkNTT::MontgomeryMul<SharkFloatParams>( \
    DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t a, uint64_t b); \
    template uint64_t SharkNTT::ToMontgomery<SharkFloatParams>(uint64_t x); \
    template uint64_t SharkNTT::ToMontgomery<SharkFloatParams>( \
    DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t x); \
    template uint64_t SharkNTT::FromMontgomery<SharkFloatParams>(uint64_t x); \
    template uint64_t SharkNTT::FromMontgomery<SharkFloatParams>( \
    DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t x); \
    template uint64_t SharkNTT::MontgomeryPow<SharkFloatParams>(uint64_t a_mont, uint64_t e); \
    template uint64_t SharkNTT::MontgomeryPow<SharkFloatParams>( \
    DebugHostCombo<SharkFloatParams> & debugCombo, uint64_t a_mont, uint64_t e); \
    template void SharkNTT::CopyRootsToCuda<SharkFloatParams>(SharkNTT::RootTables & outT, \
    const SharkNTT::RootTables &inT); \
    template void SharkNTT::DestroyRoots<SharkFloatParams>(bool cuda, SharkNTT::RootTables &T); \
    /* end */

ExplicitlyInstantiate(SharkParamsDbl1);
ExplicitlyInstantiate(SharkParamsDbl2);
ExplicitlyInstantiate(SharkParamsDbl3);
ExplicitlyInstantiate(SharkParamsDbl4);
ExplicitlyInstantiate(SharkParamsDbl5);
ExplicitlyInstantiate(SharkParamsDbl6);
ExplicitlyInstantiate(SharkParamsDbl7);
ExplicitlyInstantiate(SharkParamsDbl8);
ExplicitlyInstantiate(SharkParamsDbl9);
ExplicitlyInstantiate(SharkParamsDbl10);
ExplicitlyInstantiate(SharkParamsDbl11);
ExplicitlyInstantiate(SharkParamsDbl12);

#undef ExplicitlyInstantiate
