// Auto-generated explicit instantiation TU.
// Batch: HpSharkFloat_Conversions
// Tag: Dbl (SharkParamsDbl1..12, double SubType)
// This file is generated by gen_inst_files.cpp.

#include "..\HpSharkFloat_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template class HpSharkFloat<SharkFloatParams>; \
    template std::string Uint32ToMpf<SharkFloatParams>( \
    const uint32_t *array, int32_t pow64Exponent, mpf_t &mpf_val); \
    template std::string MpfToString<SharkFloatParams>(const mpf_t mpf_val, size_t precInBits); \
    /* end */

ExplicitlyInstantiate(SharkParamsDbl1);
ExplicitlyInstantiate(SharkParamsDbl2);
ExplicitlyInstantiate(SharkParamsDbl3);
ExplicitlyInstantiate(SharkParamsDbl4);
ExplicitlyInstantiate(SharkParamsDbl5);
ExplicitlyInstantiate(SharkParamsDbl6);
ExplicitlyInstantiate(SharkParamsDbl7);
ExplicitlyInstantiate(SharkParamsDbl8);
ExplicitlyInstantiate(SharkParamsDbl9);
ExplicitlyInstantiate(SharkParamsDbl10);
ExplicitlyInstantiate(SharkParamsDbl11);
ExplicitlyInstantiate(SharkParamsDbl12);

#undef ExplicitlyInstantiate
