// Auto-generated explicit instantiation TU.
// Batch: HpSharkFloat_Conversions
// Tag: NR (SharkParamsNR1..12, float SubType)
// This file is generated by gen_inst_files.cpp.

#include "../HpSharkFloat_cu.h"

#define ExplicitlyInstantiate(SharkFloatParams) \
    template class HpSharkFloat<SharkFloatParams>; \
    template std::string Uint32ToMpf<SharkFloatParams>( \
    const uint32_t *array, int32_t pow64Exponent, mpf_t &mpf_val); \
    template std::string MpfToString<SharkFloatParams>(const mpf_t mpf_val, size_t precInBits); \
    /* end */

ExplicitlyInstantiate(SharkParamsNR1);
ExplicitlyInstantiate(SharkParamsNR2);
ExplicitlyInstantiate(SharkParamsNR3);
ExplicitlyInstantiate(SharkParamsNR4);
ExplicitlyInstantiate(SharkParamsNR5);
ExplicitlyInstantiate(SharkParamsNR6);
ExplicitlyInstantiate(SharkParamsNR7);
ExplicitlyInstantiate(SharkParamsNR8);
ExplicitlyInstantiate(SharkParamsNR9);
ExplicitlyInstantiate(SharkParamsNR10);
ExplicitlyInstantiate(SharkParamsNR11);
ExplicitlyInstantiate(SharkParamsNR12);

#undef ExplicitlyInstantiate
