#!/usr/bin/env python3
"""Generate a chunked C++ coordinate header from a FractalShark clipboard dump."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import sys


DEFAULT_CHUNK_SIZE = 96
NUMBER_PATTERN = re.compile(r"[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?\Z")
FIELD_PATTERNS = {
    "Center X": re.compile(r'^Center X:\s*"(?P<value>[^"]+)"\s*$', re.MULTILINE),
    "Center Y": re.compile(r'^Center Y:\s*"(?P<value>[^"]+)"\s*$', re.MULTILINE),
    "zoomFactor": re.compile(r'^zoomFactor:\s*"(?P<value>[^"]+)"\s*$', re.MULTILINE),
}


def ParseArguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="Clipboard dump containing Center X, Center Y, and zoomFactor")
    parser.add_argument("output", type=Path, help="Generated C++ header path")
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=DEFAULT_CHUNK_SIZE,
        help=f"Maximum characters per adjacent C++ string literal (default: {DEFAULT_CHUNK_SIZE})",
    )
    arguments = parser.parse_args()
    if arguments.chunk_size <= 0:
        parser.error("--chunk-size must be positive")
    return arguments


def ExtractField(text: str, fieldName: str) -> str:
    matches = FIELD_PATTERNS[fieldName].findall(text)
    if len(matches) != 1:
        raise ValueError(f"expected exactly one {fieldName} field, found {len(matches)}")

    value = matches[0]
    if not value.isascii() or not NUMBER_PATTERN.fullmatch(value):
        raise ValueError(f"{fieldName} is not an ASCII decimal number")
    return value


def Sha256(value: str) -> str:
    return hashlib.sha256(value.encode("ascii")).hexdigest()


def FileSha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def RenderStringLiteral(name: str, value: str, chunkSize: int) -> list[str]:
    lines = [f"[[maybe_unused]] const char *{name} ="]
    lines.extend(f'"{value[index:index + chunkSize]}"' for index in range(0, len(value), chunkSize))
    lines[-1] += ";"
    return lines


def RenderHeader(inputPath: Path, values: dict[str, str], chunkSize: int) -> str:
    inputHash = FileSha256(inputPath)
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/generate_large_coords.py. Do not edit by hand.",
        f"// Source: {inputPath.name} (SHA-256: {inputHash})",
        f"// Center X SHA-256: {Sha256(values['Center X'])}",
        f"// Center Y SHA-256: {Sha256(values['Center Y'])}",
        f"// zoomFactor SHA-256: {Sha256(values['zoomFactor'])}",
        "",
        "#if defined(__clang__)",
        "#pragma clang diagnostic push",
        "#pragma clang diagnostic ignored \"-Woverlength-strings\"",
        "#endif",
        "",
    ]
    lines.extend(RenderStringLiteral("strX", values["Center X"], chunkSize))
    lines.append("")
    lines.extend(RenderStringLiteral("strY", values["Center Y"], chunkSize))
    lines.append("")
    lines.extend(RenderStringLiteral("strZoomFactor", values["zoomFactor"], chunkSize))
    lines.extend(
        [
            "",
            "#if defined(__clang__)",
            "#pragma clang diagnostic pop",
            "#endif",
            "",
        ]
    )
    return "\r\n".join(lines)


def main() -> int:
    arguments = ParseArguments()
    inputPath = arguments.input.resolve()
    outputPath = arguments.output.resolve()

    try:
        text = inputPath.read_text(encoding="utf-8-sig")
        values = {fieldName: ExtractField(text, fieldName) for fieldName in FIELD_PATTERNS}
    except (OSError, UnicodeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    outputPath.parent.mkdir(parents=True, exist_ok=True)
    outputPath.write_bytes(RenderHeader(inputPath, values, arguments.chunk_size).encode("ascii"))

    print(f"Generated {outputPath}")
    for fieldName, value in values.items():
        print(f"{fieldName}: length={len(value)} sha256={Sha256(value)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
